package recovery

import (
	"bytes"
	"strings"
	"testing"
	"time"

	"github.com/dbtrail/dbtrail/internal/parser"
	"github.com/dbtrail/dbtrail/internal/query"
)

var order2156T0 = time.Date(2026, 10, 5, 12, 0, 0, 0, time.UTC)

// lockWaitRows is #2151's first shape as a fetch returns it. Session B's
// UPDATE (event 2) started at T0 and waited on the row lock; session A's
// (event 1) started 2 s later and committed first. The binary log holds A
// then B: seed to A, then A to B.
func lockWaitRows(fileA, fileB string, posA, posB uint64) []query.ResultRow {
	upd := func(id uint64, file string, pos uint64, at time.Time, before, after string) query.ResultRow {
		return query.ResultRow{
			EventID: id, BinlogFile: file, StartPos: pos, EventTimestamp: at,
			SchemaName: "shop", TableName: "t", EventType: parser.EventUpdate, PKValues: "1",
			RowBefore: map[string]any{"id": float64(1), "v": before},
			RowAfter:  map[string]any{"id": float64(1), "v": after},
		}
	}
	return []query.ResultRow{
		upd(2, fileB, posB, order2156T0, "A", "B"),
		upd(1, fileA, posA, order2156T0.Add(2*time.Second), "seed", "A"),
	}
}

func yes([]query.ResultRow) bool { return true }
func no([]query.ResultRow) bool  { return false }

// script2156 renders rows and returns the script without its first line (the
// generation time), plus the generator for its decision.
func script2156(t *testing.T, g *Generator, rows []query.ResultRow) string {
	t.Helper()
	var buf bytes.Buffer
	if _, err := g.GenerateSQLFromRows(rows, &buf); err != nil {
		t.Fatalf("GenerateSQLFromRows: %v", err)
	}
	_, rest, ok := strings.Cut(buf.String(), "\n")
	if !ok || !strings.HasPrefix(buf.String(), "-- Generated by bintrail recover at ") {
		t.Fatalf("unexpected first line:\n%s", buf.String())
	}
	return rest
}

// undoOrder is the event ids of the "-- [id] reverse" lines, in script order.
func undoOrder(script string) string {
	var ids []string
	for _, line := range strings.Split(script, "\n") {
		if rest, ok := strings.CutPrefix(line, "-- ["); ok {
			id, _, _ := strings.Cut(rest, "]")
			ids = append(ids, id)
		}
	}
	return strings.Join(ids, ",")
}

// The lock wait: with the rule the script undoes B and then A, and the row
// ends on the value before both. Without it (a generator that was not opted
// in: recover-cascade, the agent) the order is the one handed in, reversed.
func TestBinlogOrder_lockWaitIsUndoneInCommitOrder(t *testing.T) {
	const f = "binlog.000007"

	plain := script2156(t, New(nil, nil), lockWaitRows(f, f, 400, 900))
	if got := undoOrder(plain); got != "1,2" {
		t.Fatalf("a generator without SetBinlogOrder undid %s; it must reverse what it is handed (1,2)", got)
	}

	g := New(nil, nil)
	g.SetBinlogOrder(yes)
	got := script2156(t, g, lockWaitRows(f, f, 400, 900))
	if order := undoOrder(got); order != "2,1" {
		t.Fatalf("undo order = %s, want 2,1 (B, the last in the binary log, first)\n%s", order, got)
	}
	if !g.OrderDecision().Sorted() {
		t.Fatalf("OrderDecision = %+v, want sorted", g.OrderDecision())
	}
	// The statements, in order: B's values back to A, then A's back to seed.
	first := strings.Index(got, "SET `id` = 1, `v` = 'A' WHERE `id` = 1 AND `v` = 'B'")
	second := strings.Index(got, "SET `id` = 1, `v` = 'seed' WHERE `id` = 1 AND `v` = 'A'")
	if first < 0 || second < 0 || first > second {
		t.Fatalf("statements missing or out of order (%d, %d):\n%s", first, second, got)
	}
	const note = "-- NOTE: 2 of these changes were written to the binary log in a different order than their\n" +
		"--       statements started (a statement that waited for a row lock, or ran long). They are undone\n" +
		"--       in the reverse of binary log order, which is commit order, so the `at` times of the\n" +
		"--       statements below are not all in sequence.\n" +
		"-- NOTE: applying this script"
	if !strings.Contains(got, note) {
		t.Fatalf("the header does not carry the note:\n%s", got)
	}
	if strings.Contains(got, "WARNING") {
		t.Fatalf("a sorted script carries a warning:\n%s", got)
	}
}

// Every case where binary log order cannot be established ends in the order
// handed in, reversed, with a WARNING in the header: the body is the body of a
// generator that was not opted in, byte for byte, and the header is that
// generator's header plus the warning.
func TestBinlogOrder_whatCannotBeProvenKeepsTheOrderAndWarns(t *testing.T) {
	for _, tc := range []struct {
		name  string
		rows  func() []query.ResultRow
		proof func([]query.ResultRow) bool
		warn  string
	}{
		{"a change with no position", func() []query.ResultRow { return lockWaitRows("binlog.000007", "", 400, 0) }, yes,
			"-- WARNING: order of the changes: 1 of 2 changes carry no binary log position"},
		{"two binary log names", func() []query.ResultRow { return lockWaitRows("a-bin.000001", "b-bin.000001", 400, 900) }, yes,
			"with different names (a-bin, b-bin)"},
		{"ids that do not follow the binary log", func() []query.ResultRow { return lockWaitRows("binlog.000007", "binlog.000007", 400, 900) }, no,
			"this index cannot show which one is right"},
		{"no index to ask", func() []query.ResultRow { return lockWaitRows("binlog.000007", "binlog.000007", 400, 900) }, nil,
			"this index cannot show which one is right"},
		// RESET MASTER between the two: event 1 started first and is in file
		// 50, event 2 started second and is in file 1. Time order is right.
		{"the numbering restarted", func() []query.ResultRow {
			r := lockWaitRows("binlog.000050", "binlog.000001", 400, 900)
			r[0], r[1] = r[1], r[0]
			r[0].EventTimestamp, r[1].EventTimestamp = order2156T0, order2156T0.Add(time.Hour)
			return r
		}, yes,
			"the binary log position goes down inside this time range"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			plain := script2156(t, New(nil, nil), tc.rows())
			g := New(nil, nil)
			g.SetBinlogOrder(tc.proof)
			got := script2156(t, g, tc.rows())

			if order := undoOrder(got); order != undoOrder(plain) || len(order) != 3 {
				t.Fatalf("undo order = %s, want the order handed in, reversed (%s)", order, undoOrder(plain))
			}
			if !strings.Contains(got, tc.warn) {
				t.Fatalf("header does not hold %q:\n%s", tc.warn, got)
			}
			warn := g.OrderDecision().Warning()
			if warn == "" || g.OrderDecision().Sorted() {
				t.Fatalf("OrderDecision = %+v, want a refusal with a warning", g.OrderDecision())
			}
			// Take the warning paragraph out: what is left is the plain script.
			start := strings.Index(got, "-- WARNING: ")
			end := strings.Index(got, "-- NOTE: applying this script")
			if start < 0 || end < start {
				t.Fatalf("warning paragraph not where expected:\n%s", got)
			}
			for _, line := range strings.Split(strings.TrimSuffix(got[start:end], "\n"), "\n") {
				if !strings.HasPrefix(line, "-- ") || len(line) > commentWidth {
					t.Fatalf("warning line is not a comment of at most %d bytes: %q", commentWidth, line)
				}
			}
			if stripped := got[:start] + got[end:]; stripped != plain {
				t.Fatalf("apart from the warning the script differs from one generated without the rule.\n--- with ---\n%s\n--- without ---\n%s", stripped, plain)
			}
			if strings.Contains(got, "written to the binary log in a different order") {
				t.Fatalf("an unsorted script carries the sorted note:\n%s", got)
			}
		})
	}
}

// Nothing changes, byte for byte, for a window whose two orders agree, for a
// PostgreSQL index, and for a single change.
func TestBinlogOrder_byteIdenticalWhereThereIsNothingToDecide(t *testing.T) {
	agree := func() []query.ResultRow {
		rows := lockWaitRows("binlog.000007", "binlog.000007", 900, 400)
		// Event 2 at 400 started first, event 1 at 900 second: both orders say 2, 1.
		return rows
	}
	pg := func() []query.ResultRow { return lockWaitRows("0/FFFFFFFF", "1/5", 9, 5) }
	mustNotAsk := func([]query.ResultRow) bool {
		t.Fatal("the index was asked although there was nothing to decide")
		return false
	}
	for _, tc := range []struct {
		name    string
		dialect Dialect
		rows    func() []query.ResultRow
	}{
		{"the two orders agree", MySQLDialect, agree},
		{"one change", MySQLDialect, func() []query.ResultRow { return lockWaitRows("binlog.000007", "binlog.000007", 400, 900)[:1] }},
		{"PostgreSQL dialect, LSN rows", PostgresDialect, pg},
		// The dialect read can fail and default to MySQL: LSN rows alone must
		// still be left alone, silently.
		{"MySQL dialect, LSN rows", MySQLDialect, pg},
		// And a PostgreSQL generator never applies the rule, whatever the rows hold.
		{"PostgreSQL dialect, rows that would sort", PostgresDialect, func() []query.ResultRow { return lockWaitRows("binlog.000007", "binlog.000007", 400, 900) }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			plain := script2156(t, NewForDialect(nil, nil, tc.dialect), tc.rows())
			g := NewForDialect(nil, nil, tc.dialect)
			g.SetBinlogOrder(mustNotAsk)
			if got := script2156(t, g, tc.rows()); got != plain {
				t.Fatalf("the script changed.\n--- with ---\n%s\n--- without ---\n%s", got, plain)
			}
			if w := g.OrderDecision().Warning(); w != "" || g.OrderDecision().Sorted() {
				t.Fatalf("OrderDecision = %+v", g.OrderDecision())
			}
		})
	}
}

// A generator used twice reports the decision of the LAST generation, not a
// stale warning from the one before.
func TestBinlogOrder_decisionIsPerGeneration(t *testing.T) {
	g := New(nil, nil)
	g.SetBinlogOrder(no)
	script2156(t, g, lockWaitRows("binlog.000007", "binlog.000007", 400, 900))
	if g.OrderDecision().Warning() == "" {
		t.Fatal("no warning for an unproven index")
	}
	script2156(t, g, lockWaitRows("binlog.000007", "binlog.000007", 400, 900)[:1])
	if g.OrderDecision().Warning() != "" {
		t.Fatalf("stale warning after a generation with nothing to decide: %q", g.OrderDecision().Warning())
	}
}

// A binary log file name is data read from the index. One holding a line
// break must not end the header comment and start a line of SQL.
func TestBinlogOrder_warningCannotBreakOutOfTheComment(t *testing.T) {
	g := New(nil, nil)
	g.SetBinlogOrder(yes)
	got := script2156(t, g, lockWaitRows("a-bin.000001", "evil\nDROP TABLE t; --.000001", 400, 900))
	header, _, ok := strings.Cut(got, "\nBEGIN;\n")
	if !ok {
		t.Fatalf("no BEGIN:\n%s", got)
	}
	for _, line := range strings.Split(header, "\n") {
		if line != "" && !strings.HasPrefix(line, "--") {
			t.Fatalf("a header line is not a comment: %q\n%s", line, header)
		}
	}
	if !strings.Contains(header, "DROP") {
		t.Fatalf("the hostile name did not reach the header; this case tests nothing:\n%s", header)
	}
}

func TestWriteCommentParagraph(t *testing.T) {
	var buf bytes.Buffer
	writeCommentParagraph(&buf, "-- NOTE: ", strings.Repeat("word ", 40))
	lines := strings.Split(strings.TrimSuffix(buf.String(), "\n"), "\n")
	if len(lines) < 2 {
		t.Fatalf("not wrapped: %q", buf.String())
	}
	for i, line := range lines {
		want := "--       word"
		if i == 0 {
			want = "-- NOTE: word"
		}
		if !strings.HasPrefix(line, want) || len(line) > commentWidth || strings.HasSuffix(line, " ") {
			t.Fatalf("line %d = %q", i, line)
		}
	}
	buf.Reset()
	writeCommentParagraph(&buf, "-- NOTE: ", strings.Repeat("x", 300))
	if got := buf.String(); got != "-- NOTE: "+strings.Repeat("x", 300)+"\n" {
		t.Fatalf("a word longer than the line was cut or lost: %q", got)
	}
}
