package recovery

import (
	"bytes"
	"slices"
	"strings"
	"testing"

	"github.com/dbtrail/dbtrail/internal/parser"
	"github.com/dbtrail/dbtrail/internal/query"
)

// assertStatementEnds is the guard the chunked MCP delivery relies on (#1438):
// every recorded end must sit just past a `;` and its newline, strictly
// increasing, inside the text. Concatenating chunks cut on ANY increasing
// offsets reproduces the script, so `concat == whole` cannot see a rebase that
// forgot the preamble; this can.
func assertStatementEnds(t *testing.T, text string, ends []int, wantCount int) {
	t.Helper()
	if len(ends) != wantCount {
		t.Fatalf("%d statement end(s) recorded, want %d", len(ends), wantCount)
	}
	prev := 0
	for i, e := range ends {
		if e <= prev || e > len(text) || e < 2 || text[e-1] != '\n' || text[e-2] != ';' {
			t.Fatalf("end %d (byte %d) does not close a statement; text around it: %q", i+1, e, around(text, e))
		}
		prev = e
	}
}

func around(text string, e int) string {
	lo, hi := max(0, e-20), min(len(text), e+5)
	return text[lo:hi]
}

func TestGenerateSQLFromRowsIndexed_endsCloseStatements(t *testing.T) {
	g := newGen()
	rows := []query.ResultRow{
		{EventID: 1, SchemaName: "db", TableName: "t", EventType: parser.EventInsert,
			RowAfter: map[string]any{"id": float64(1), "note": "a;\nb"}},
		{EventID: 2, SchemaName: "db", TableName: "t", EventType: parser.EventDelete,
			RowBefore: map[string]any{"id": float64(2), "note": "x"}},
		{EventID: 3, SchemaName: "db", TableName: "t", EventType: parser.EventUpdate,
			RowBefore: map[string]any{"id": float64(3), "v": float64(1)},
			RowAfter:  map[string]any{"id": float64(3), "v": float64(2)}},
	}
	var buf bytes.Buffer
	n, ends, err := g.GenerateSQLFromRowsIndexed(slices.Clone(rows), &buf) // the generator reverses its input in place
	if err != nil {
		t.Fatal(err)
	}
	text := buf.String()
	assertStatementEnds(t, text, ends, n)

	// The first end lies past the preamble (the rebase onto the counting
	// writer happened) and the segments are the reversal statements, one each.
	if pre := strings.Index(text, "BEGIN;\n"); pre < 0 || ends[0] <= pre {
		t.Fatalf("first end (%d) sits inside the preamble (BEGIN at %d)", ends[0], pre)
	}
	prev := 0
	for i, e := range ends {
		// One reversal per segment. Counting ";\n" would be wrong here on
		// purpose: the first row's value holds one, which is exactly why the
		// offsets are recorded rather than scanned.
		seg := text[prev:e]
		if strings.Count(seg, "`db`.`t`") != 1 {
			t.Errorf("segment %d is not one statement: %q", i+1, seg)
		}
		prev = e
	}
	// The whole script is unchanged by indexing.
	var plain bytes.Buffer
	if _, err := g.GenerateSQLFromRows(slices.Clone(rows), &plain); err != nil {
		t.Fatal(err)
	}
	if a, b := strip(plain.String()), strip(text); a != b {
		t.Errorf("GenerateSQLFromRowsIndexed and GenerateSQLFromRows render different scripts.\n--- plain ---\n%s\n--- indexed ---\n%s", a, b)
	}
}

// strip drops the generated-at line, the one byte-level difference between two
// builds of the same script.
func strip(s string) string {
	var out []string
	for line := range strings.SplitSeq(s, "\n") {
		if strings.HasPrefix(line, "-- Generated by bintrail recover at ") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}
