-- DuckDB views over a bintrail archive layout.
-- Generated by bintrail v0.50.0 at 2026-05-01T12:00:00Z.
--
-- THIS FILE IS A SNAPSHOT OF THE LAYOUT, NOT A LIVE BINDING. The globs below
-- keep picking up newly rotated partitions on their own, but the baseline
-- state views point at ONE snapshot. Re-run `bintrail views` (or download the
-- file again from the console) after taking or refreshing a baseline, and
-- whenever archive sources are added or removed.
--
-- A daemon running `bintrail-console watch --baseline-refresh-interval`
-- publishes a new snapshot every interval, and nothing regenerates this file.
-- Any state view below stays bound to the snapshot it was generated against,
-- with no error and no warning: its rows just stop changing. Regenerate this
-- file on the same schedule that refresh runs on.
--
-- Nothing here writes: every view is a read over Parquet files you already own.
--
-- Archive sources (an archive registered with both a local path and an S3
-- location is listed by its S3 location, so those reads work from another
-- machine; a local path below means the registry holds no S3 location this
-- file can use):
--   /data/archives/bintrail_id=11111111-2222-3333-4444-555555555555
--   s3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000
-- Baseline snapshot:
--   s3://my-bucket/baselines/ at 2026-04-30T03:00:00Z (4 table(s))

-- Timestamps are recorded in UTC, and the archives carry the zone, so the
-- session's setting decides how they print and where date_trunc puts a day
-- boundary. Pinned to UTC here so the numbers match the console. Change it if
-- you would rather read in your own zone.
SET TimeZone = 'UTC';

-- S3 setup, mirroring what bintrail's own DuckDB sessions configure.
INSTALL httpfs; LOAD httpfs;
INSTALL aws; LOAD aws;
CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1');
-- This secret lives only in this DuckDB session. Views persist in a database
-- file; secrets do not. Reopening that file later and querying S3 fails with
-- "No credentials are provided": run this file again in every session that
-- reads S3 (`.read views.sql`, or `duckdb -init views.sql your.db`).
-- Do not make it PERSISTENT: DuckDB would resolve your credential chain now
-- and store the resulting keys on disk.
-- No credentials appear in this file by design. If the credential chain is not
-- available where you run this, replace the secret above with explicit keys:
--   CREATE OR REPLACE SECRET bintrail_s3_chain (
--     TYPE s3, KEY_ID '…', SECRET '…', REGION '…');

-- state_<schema>_<table>: each table's full contents as of the baseline snapshot.
--
-- These are the SNAPSHOT's rows, not the table's current state: changes after
-- the snapshot live in the `events` view.
-- To materialize a later point in time, use `bintrail reconstruct`. Folding
-- the deltas back onto a baseline is what that command does, and it is not
-- expressible as a view.
--
-- DECIMAL and NUMERIC columns are stored as text, so that a value MySQL can
-- hold is never rounded to fit a narrower type. The views below cast them
-- back to DECIMAL with the precision and scale the column was declared with,
-- so sum() and the rest work on them directly.
-- Columns wider than 38 digits have no DuckDB DECIMAL to be cast to, so they
-- stay text. They are named below. Cast them yourself when you need
-- arithmetic; DOUBLE works if an approximate result is acceptable.
-- Some files carry no column types, so their views cast nothing and every
-- decimal column in them reads as text. Those tables are named below. A
-- baseline older than this feature gains the casts when it is next taken or
-- refreshed; a PostgreSQL-source baseline stores all its values as text and
-- will not gain them. If a footer could not be read at all, the bintrail log
-- has the error.
-- state_legacy_db_audit_log: this file carries no column types, so nothing is cast; decimal columns read as text
CREATE OR REPLACE VIEW "state_legacy_db_audit_log" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/Legacy-DB/Audit Log.parquet');
CREATE OR REPLACE VIEW "state_shop_order_items" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/order_items.parquet');
CREATE OR REPLACE VIEW "state_shop_orders" AS
  SELECT * REPLACE (CAST("total" AS DECIMAL(10,2)) AS "total", CAST("tax_rate" AS DECIMAL(6,4)) AS "tax_rate")
  FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/orders.parquet');
-- state_shop_order_items_2: weight is DECIMAL(65,30), wider than DuckDB's 38 digits (left as text)
CREATE OR REPLACE VIEW "state_shop_order_items_2" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop_order/items.parquet');

-- events: every archived binlog event, across all archive sources.
--
-- union_by_name is required, not cosmetic: archives written before a column
-- existed simply lack it, and those files must read back with NULLs rather
-- than failing the whole scan. A column absent from EVERY archived file is
-- still an error here: drop it from the SELECT if you hit that on an old
-- archive. (The grouped form this file is not using pads it with NULL.)
--
-- COST: union_by_name makes DuckDB open one Parquet footer per archived file
-- to unify the schema, and a view re-binds on every statement, so the wait
-- before the first row grows with the archive.
--
-- SCOPE: these are the ARCHIVED events only. Partitions rotation has not
-- archived yet exist solely in the index, so the most recent window is
-- absent here and reads as if nothing happened.
-- Add a leg over the index by regenerating with --include-live:
--   bintrail views --index-dsn ... --include-live
CREATE OR REPLACE VIEW "events" AS
  SELECT
    "bintrail_id", "event_date", "event_hour",
    CAST("event_id" AS BIGINT) AS "event_id",
    "binlog_file",
    "start_pos",
    "end_pos",
    "event_timestamp",
    "gtid",
    "connection_id",
    "schema_name",
    "table_name",
    CAST("event_type" AS INTEGER) AS "event_type_code",
    CASE "event_type"
      WHEN 1 THEN 'INSERT'
      WHEN 2 THEN 'UPDATE'
      WHEN 3 THEN 'DELETE'
      ELSE CAST("event_type" AS VARCHAR)
    END AS "event_type",
    "pk_values",
    "changed_columns",
    "row_before",
    "row_after",
    CAST("schema_version" AS INTEGER) AS "schema_version",
    "query_text",
    "query_hash",
    "commit_ts_us",
    CASE WHEN "commit_ts_us" IS NULL THEN NULL
         ELSE make_timestamp(CAST("commit_ts_us" AS BIGINT)) END AS "commit_time"
  FROM read_parquet(
    [
      '/data/archives/bintrail_id=11111111-2222-3333-4444-555555555555/event_date=*/event_hour=*/*.parquet',
      's3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000/event_date=*/event_hour=*/*.parquet'
    ],
    hive_partitioning = true,
    union_by_name = true
  );

