-- DuckDB views over a bintrail archive layout.
-- Generated by bintrail v0.50.0 at 2026-05-01T12:00:00Z.
--
-- THIS FILE IS A SNAPSHOT OF THE LAYOUT, NOT A LIVE BINDING. The baseline state
-- views follow the `_NEWEST` pointer, so a refreshed baseline reaches them
-- on its own. What does NOT follow is this file's idea of the SHAPE of the
-- data: which views exist, and how each DECIMAL column is read, were decided
-- from the snapshot named below. Re-run `bintrail views` (or download the file
-- again from the web interface) after a table is added or dropped, after a
-- column changes type, and whenever archive sources are added or removed.
--
-- Which of those you will notice follows one rule: this file names only the
-- PATHS and the DECIMAL columns, so only those two can fail. A table that
-- leaves the newest snapshot is caught by the check below, which names the
-- table and stops before any view is created; a DECIMAL column renamed or
-- dropped fails the script at its own view.
-- Everything else is QUIET, because `SELECT *` passes it through untouched:
-- a table added to the source has no view here, a DECIMAL whose scale grew is
-- read at the old scale with the extra digits rounded away, a column that
-- changes to some other type arrives as whatever the new file holds (an
-- ORDER BY can start sorting text), and an archive source added later is
-- simply not here. None of those raise an error.
--
-- A daemon running `bintrail-console watch --baseline-refresh-interval`
-- publishes a new snapshot every interval, and the state views below move to
-- it once it completes. They resolve which one ONCE, when this file is read,
-- so every state view shows the same snapshot and none of them can drift
-- apart mid-session. A refresh published while you are working is picked up
-- by reading this file again, which is already what an S3 session needs to do
-- for the secret above.
-- Which snapshot is newest comes from the root's `_NEWEST` pointer, which a
-- baseline upload moves. It stays on the previous snapshot (no error here) when
-- a snapshot is published by a build that predates the pointer, copied into the
-- root by hand, or uploaded while the pointer could not be written (the upload
-- logs that as an ERROR); and two processes uploading to one root can move it
-- back. If the pointer is deleted, reading this file fails with a 404 on it:
-- generate the file again and it lists the root instead.
-- That choice lives in a SESSION variable, and views persist while a session
-- variable does not: a database file that saved these views lists them all in
-- a new session, and every read raises until this file's SET VARIABLE
-- statement is run again in that session.
--
-- Nothing here writes: every view is a read over Parquet files you already own.
--
-- Archive sources (an archive registered with both a local path and an S3
-- location is listed by its S3 location, so those reads work from another
-- machine; a local path below means the registry holds no S3 location this
-- file can use):
--   /data/archives/bintrail_id=11111111-2222-3333-4444-555555555555
--   s3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000
-- Baseline snapshot:
--   s3://my-bucket/baselines/ at 2026-04-30T03:00:00Z (5 table(s))
--   read through the snapshot s3://my-bucket/baselines/_NEWEST names, which is that one right now

-- Timestamps are recorded in UTC, and the archives carry the zone, so the
-- session's setting decides how they print and where date_trunc puts a day
-- boundary. Pinned to UTC here so the numbers match the web interface. Change
-- it if you would rather read in your own zone.
SET TimeZone = 'UTC';

-- S3 setup, mirroring what bintrail's own DuckDB sessions configure.
INSTALL httpfs; LOAD httpfs;
INSTALL aws; LOAD aws;
CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1');
-- This secret lives only in this DuckDB session. Views persist in a database
-- file; secrets do not. Reopening that file later and querying S3 fails with
-- "No credentials are provided": run this file again in every session that
-- reads S3 (`.read views.sql`, or `duckdb -init views.sql your.db`).
-- Do not make it PERSISTENT: DuckDB would resolve your credential chain now
-- and store the resulting keys on disk.
-- No credentials appear in this file by design. If the credential chain is not
-- available where you run this, replace the secret above with explicit keys:
--   CREATE OR REPLACE SECRET bintrail_s3_chain (
--     TYPE s3, KEY_ID '…', SECRET '…', REGION '…');

-- <schema>.<table>: each table's full contents as of the snapshot the
-- `_NEWEST` pointer names, chosen when the view is read.
-- Each table keeps its own name: SELECT * FROM demo.prices, and a name DuckDB
-- cannot read bare is quoted, as in demo."order.items".
-- Do not open this in a database file named after one of these schemas:
-- in demo.db, demo.prices is ambiguous and the load stops at that view.
--
-- These are the SNAPSHOT's rows, not the table's current state: changes after
-- the snapshot are not in this file. `bintrail views --include-events`
-- adds the view that holds them, as does the change-log box in the
-- web interface.
-- To materialize a later point in time, use `bintrail reconstruct`. Folding
-- the deltas back onto a baseline is what that command does, and it is not
-- expressible as a view.
--
-- DECIMAL and NUMERIC columns are stored as text, so that a value MySQL can
-- hold is never rounded to fit a narrower type. The views below cast them
-- back to DECIMAL with the precision and scale the column was declared with,
-- so sum() and the rest work on them directly.
-- Columns wider than 38 digits have no DuckDB DECIMAL to be cast to, so they
-- stay text. They are named below. Cast them yourself when you need
-- arithmetic; DOUBLE works if an approximate result is acceptable.
-- Some files carry no column types, so their views cast nothing and every
-- decimal column in them reads as text. Those tables are named below. A
-- baseline older than this feature gains the casts when it is next taken or
-- refreshed; a PostgreSQL-source baseline stores all its values as text and
-- will not gain them. If a footer could not be read at all, the bintrail log
-- has the error.
--
-- SELECT * on these views returns each table's columns sorted by name, the
-- order the snapshot files hold them in, not the order the table declares
-- them in. Name the columns wherever their position matters. A file that
-- follows later snapshots carries no column list on purpose: a column dropped
-- at the source would stop every query on its table until the file is
-- generated again.
-- Off while the newest snapshot is chosen, so reading this file again in the
-- same session sees a refresh; back on below for the snapshot's own files.
SET enable_http_metadata_cache = false;

-- The snapshot every state view below reads through: the one _NEWEST names,
-- read once, when this file is read. Each baseline publish moves that pointer,
-- so reading this whole file again picks up a refresh without reopening the
-- session, and every view follows it together. Running this one statement
-- again does not: the file ends with a cache on that remembers the pointer.
SET VARIABLE bintrail_newest_snapshot = (
  SELECT CASE WHEN regexp_full_match(trim(content, chr(32) || chr(9) || chr(13) || chr(10)), '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z')
    THEN 's3://my-bucket/baselines/' || trim(content, chr(32) || chr(9) || chr(13) || chr(10)) || '/'
    ELSE error('bintrail views: s3://my-bucket/baselines/_NEWEST does not hold a snapshot name. Refresh or re-upload a baseline to rewrite it, or generate this file again.') END
  FROM read_text('s3://my-bucket/baselines/_NEWEST'));

-- Every file of that snapshot, listed once. The views below pick their own
-- files out of this list instead of each asking the store again. To pick up
-- a refresh, read this whole file again. A session that has the variable
-- above and not this one still reads that snapshot, asking the store each
-- time.
SET VARIABLE bintrail_snapshot_files = (SELECT {'dir': getvariable('bintrail_newest_snapshot'), 'files': list(file ORDER BY file COLLATE C)} FROM glob(getvariable('bintrail_newest_snapshot') || '**/*'));

-- Every table below has to still be in that snapshot. A table dropped at the
-- source leaves it, and DuckDB binds a view when it is created, so without
-- this the script would stop at that one view and never define the rest.
SET VARIABLE bintrail_missing_tables = (
  SELECT string_agg(t, ', ' ORDER BY t) FROM (VALUES
    ('Legacy-DB/Audit Log.parquet'),
    ('shop/ORDER_ITEMS.parquet'),
    ('shop/order_items.parquet'),
    ('shop/orders.parquet'),
    ('shop_order/items.parquet')
  ) AS x(t)
  WHERE (getvariable('bintrail_newest_snapshot') || t) COLLATE C NOT IN (SELECT unnest(struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files')) COLLATE C));
SET VARIABLE bintrail_tables_checked = (SELECT CASE WHEN getvariable('bintrail_missing_tables') IS NOT NULL
  THEN error('bintrail views: these tables are not in the newest snapshot any more: ' || getvariable('bintrail_missing_tables') ||
    '. Looked in ' || getvariable('bintrail_newest_snapshot') ||
    '. If they were dropped or renamed, download this file again.') END);

-- A published snapshot's files never change, so DuckDB need not ask S3 again
-- before every query whether each one changed. This setting covers this whole
-- DuckDB session, not only these views: if the same session also reads S3
-- objects of yours that do change, turn it back off with
-- RESET enable_http_metadata_cache;
SET enable_http_metadata_cache = true;
-- Reads the footer of every file the views below open, all at once (DuckDB
-- 1.5 or newer; an older DuckDB reads one here and loads at its usual pace).
SET VARIABLE bintrail_prefetch_all = (SELECT count(*) = 2 FROM duckdb_settings() WHERE name = 'validate_external_file_cache' OR (name = 'enable_external_file_cache' AND lower(value) = 'true'));
SET VARIABLE bintrail_footers_read = (SELECT count(*) FROM parquet_file_metadata(CASE WHEN getvariable('bintrail_prefetch_all') THEN [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF regexp_matches(f, '\.parquet$|\.[0-9]{6}(-[0-9]{6})?\.(upserts|posdel)$')] ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF regexp_matches(f, '\.parquet$|\.[0-9]{6}(-[0-9]{6})?\.(upserts|posdel)$')][1:1] END));

CREATE SCHEMA IF NOT EXISTS "Legacy-DB";
CREATE SCHEMA IF NOT EXISTS "shop";
CREATE SCHEMA IF NOT EXISTS "shop_order";
-- "Legacy-DB"."Audit Log": this file carries no column types, so nothing is cast; decimal columns read as text
-- "Legacy-DB"."Audit Log": reads the table file alone because its schema could not be read. If a refresh writes changes beside the file, this view stops with an error until the views are generated again
CREATE OR REPLACE VIEW "Legacy-DB"."Audit Log" AS
  SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    ELSE getvariable('bintrail_newest_snapshot') || 'Legacy-DB/Audit Log.parquet' END)
  WHERE CASE WHEN (SELECT count(*) FROM glob(getvariable('bintrail_newest_snapshot') || 'Legacy-DB/Audit Log.[0-9][0-9][0-9][0-9][0-9][0-9].upserts')) + (SELECT count(*) FROM glob(getvariable('bintrail_newest_snapshot') || 'Legacy-DB/Audit Log.[0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].upserts')) > 0 THEN error('bintrail views: Legacy-DB.Audit Log now has a table delta beside its file, and this view reads the file alone, so it would show the table as it was when it was last written in full. Generate the views again') ELSE true END;
-- shop.ORDER_ITEMS_945701: the table shop.ORDER_ITEMS. DuckDB does not tell names apart by letter case, and shop.order_items already has that name
-- shop.ORDER_ITEMS_945701: this file carries no column types, so nothing is cast; decimal columns read as text
-- shop.ORDER_ITEMS_945701: reads the table file alone because its schema could not be read. If a refresh writes changes beside the file, this view stops with an error until the views are generated again
CREATE OR REPLACE VIEW "shop"."ORDER_ITEMS_945701" AS
  SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    ELSE getvariable('bintrail_newest_snapshot') || 'shop/ORDER_ITEMS.parquet' END)
  WHERE CASE WHEN (SELECT count(*) FROM glob(getvariable('bintrail_newest_snapshot') || 'shop/ORDER_ITEMS.[0-9][0-9][0-9][0-9][0-9][0-9].upserts')) + (SELECT count(*) FROM glob(getvariable('bintrail_newest_snapshot') || 'shop/ORDER_ITEMS.[0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].upserts')) > 0 THEN error('bintrail views: shop.ORDER_ITEMS now has a table delta beside its file, and this view reads the file alone, so it would show the table as it was when it was last written in full. Generate the views again') ELSE true END;
CREATE OR REPLACE VIEW "shop"."order_items" AS
  WITH bintrail_delta AS (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop/order_items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop/order_items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop/') + 1), '/')] END, filename=true, union_by_name=true) WHERE regexp_matches(filename, '(^|[/\\])order_items\.[0-9]{6}(-[0-9]{6})?\.upserts$') UNION ALL BY NAME SELECT NULL::VARCHAR AS "bintrail_pk", NULL::VARCHAR AS "bintrail_op" WHERE false), bintrail_latest AS (SELECT * EXCLUDE (filename) FROM bintrail_delta QUALIFY row_number() OVER (PARTITION BY "bintrail_pk" COLLATE C ORDER BY filename COLLATE C DESC) = 1) SELECT * FROM (SELECT * EXCLUDE (file_row_number) FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    ELSE getvariable('bintrail_newest_snapshot') || 'shop/order_items.parquet' END, file_row_number=true) WHERE file_row_number NOT IN (SELECT CAST("pos" AS BIGINT) FROM (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop/order_items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop/order_items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop/') + 1), '/')] END, filename=true) WHERE regexp_matches(filename, '(^|[/\\])order_items\.[0-9]{6}(-[0-9]{6})?\.posdel$') UNION ALL BY NAME SELECT NULL::BIGINT AS "pos" WHERE false) WHERE "pos" IS NOT NULL) UNION ALL BY NAME SELECT * EXCLUDE ("bintrail_pk", "bintrail_op") FROM bintrail_latest WHERE "bintrail_op" = 'u');
CREATE OR REPLACE VIEW "shop"."orders" AS
  WITH bintrail_delta AS (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop/orders.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop/orders.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop/') + 1), '/')] END, filename=true, union_by_name=true) WHERE regexp_matches(filename, '(^|[/\\])orders\.[0-9]{6}(-[0-9]{6})?\.upserts$') UNION ALL BY NAME SELECT NULL::VARCHAR AS "bintrail_pk", NULL::VARCHAR AS "bintrail_op" WHERE false), bintrail_latest AS (SELECT * EXCLUDE (filename) FROM bintrail_delta QUALIFY row_number() OVER (PARTITION BY "bintrail_pk" COLLATE C ORDER BY filename COLLATE C DESC) = 1) SELECT * REPLACE (CAST("total" AS DECIMAL(10,2)) AS "total", CAST("tax_rate" AS DECIMAL(6,4)) AS "tax_rate") FROM (SELECT * EXCLUDE (file_row_number) FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    ELSE getvariable('bintrail_newest_snapshot') || 'shop/orders.parquet' END, file_row_number=true) WHERE file_row_number NOT IN (SELECT CAST("pos" AS BIGINT) FROM (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop/orders.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop/orders.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop/') + 1), '/')] END, filename=true) WHERE regexp_matches(filename, '(^|[/\\])orders\.[0-9]{6}(-[0-9]{6})?\.posdel$') UNION ALL BY NAME SELECT NULL::BIGINT AS "pos" WHERE false) WHERE "pos" IS NOT NULL) UNION ALL BY NAME SELECT * EXCLUDE ("bintrail_pk", "bintrail_op") FROM bintrail_latest WHERE "bintrail_op" = 'u');
-- shop_order.items: weight is DECIMAL(65,30), wider than DuckDB's 38 digits (left as text)
CREATE OR REPLACE VIEW "shop_order"."items" AS
  WITH bintrail_delta AS (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop_order/items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop_order/items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[ts]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop_order/') + 1), '/')] END, filename=true, union_by_name=true) WHERE regexp_matches(filename, '(^|[/\\])items\.[0-9]{6}(-[0-9]{6})?\.upserts$') UNION ALL BY NAME SELECT NULL::VARCHAR AS "bintrail_pk", NULL::VARCHAR AS "bintrail_op" WHERE false), bintrail_latest AS (SELECT * EXCLUDE (filename) FROM bintrail_delta QUALIFY row_number() OVER (PARTITION BY "bintrail_pk" COLLATE C ORDER BY filename COLLATE C DESC) = 1) SELECT * FROM (SELECT * EXCLUDE (file_row_number) FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    ELSE getvariable('bintrail_newest_snapshot') || 'shop_order/items.parquet' END, file_row_number=true) WHERE file_row_number NOT IN (SELECT CAST("pos" AS BIGINT) FROM (SELECT * FROM read_parquet(CASE WHEN getvariable('bintrail_newest_snapshot') IS NULL
    THEN error('bintrail views: this file sets a session variable; run its SET VARIABLE statement in this session first')
    WHEN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'dir') IS DISTINCT FROM getvariable('bintrail_newest_snapshot')
    THEN [getvariable('bintrail_newest_snapshot') || 'shop_order/items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]']
    ELSE [f FOR f IN struct_extract(CAST(getvariable('bintrail_snapshot_files') AS STRUCT(dir VARCHAR, files VARCHAR[])), 'files') IF f GLOB (getvariable('bintrail_newest_snapshot') || 'shop_order/items.[0-9p][0-9a][0-9r][0-9q][0-9u][0-9e]*[tl]') AND NOT contains(substr(f, length(getvariable('bintrail_newest_snapshot') || 'shop_order/') + 1), '/')] END, filename=true) WHERE regexp_matches(filename, '(^|[/\\])items\.[0-9]{6}(-[0-9]{6})?\.posdel$') UNION ALL BY NAME SELECT NULL::BIGINT AS "pos" WHERE false) WHERE "pos" IS NOT NULL) UNION ALL BY NAME SELECT * EXCLUDE ("bintrail_pk", "bintrail_op") FROM bintrail_latest WHERE "bintrail_op" = 'u');

-- events: not included in this file.
--
-- Defining it opens one Parquet footer per archived file before it returns
-- a row, so it is left out unless asked for. Add it with `bintrail views
-- --include-events`, or the matching box in the web interface.

