-- DuckDB views over a bintrail archive layout.
-- Generated by bintrail v0.50.0 at 2026-05-01T12:00:00Z.
--
-- THIS FILE IS A SNAPSHOT OF THE LAYOUT, NOT A LIVE BINDING. The globs below
-- keep picking up newly rotated partitions, and the baseline state views
-- follow the `current` pointer, so a refreshed baseline reaches them
-- on its own. What does NOT follow is this file's idea of the SHAPE of the
-- data: which views exist, and how each DECIMAL column is read, were decided
-- from the snapshot named below. Re-run `bintrail views` (or download the file
-- again from the console) after a table is added or dropped, after a column
-- changes type, and whenever archive sources are added or removed.
--
-- Which of those you will notice follows one rule: this file names only the
-- PATHS and the DECIMAL columns, so only those two can fail. A table that
-- leaves the newest snapshot is caught by the check below, which names the
-- table and stops before any view is created; a DECIMAL column renamed or
-- dropped fails the script at its own view.
-- Everything else is QUIET, because `SELECT *` passes it through untouched:
-- a table added to the source has no view here, a DECIMAL whose scale grew is
-- read at the old scale with the extra digits rounded away, a column that
-- changes to some other type arrives as whatever the new file holds (an
-- ORDER BY can start sorting text), and an archive source added later is
-- simply not here. None of those raise an error.
--
-- A daemon running `bintrail-console watch --baseline-refresh-interval`
-- publishes a new snapshot every interval, and the state views below move to
-- it when it completes. Replacing the pointer is a single step, so no path
-- ever resolves into a half-published snapshot, and a query already running
-- finishes against the files it opened. Two views resolved either side of that
-- one step can still land on different snapshots; the window is the swap
-- itself, not the hours a file left behind would span.
--
-- Nothing here writes: every view is a read over Parquet files you already own.
--
-- Archive sources (an archive registered with both a local path and an S3
-- location is listed by its S3 location, so those reads work from another
-- machine; a local path below means the registry holds no S3 location this
-- file can use):
--   /data/archives/bintrail_id=11111111-2222-3333-4444-555555555555
--   s3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000
-- Baseline snapshot:
--   /data/baselines at 2026-04-30T03:00:00Z (4 table(s))
--   read through /data/baselines/current, which is that snapshot right now
--   a directory, so the state views resolve only where it is mounted,
--   at exactly this path

-- Timestamps are recorded in UTC, and the archives carry the zone, so the
-- session's setting decides how they print and where date_trunc puts a day
-- boundary. Pinned to UTC here so the numbers match the console. Change it if
-- you would rather read in your own zone.
SET TimeZone = 'UTC';

-- S3 setup, mirroring what bintrail's own DuckDB sessions configure.
INSTALL httpfs; LOAD httpfs;
INSTALL aws; LOAD aws;
CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1');
-- This secret lives only in this DuckDB session. Views persist in a database
-- file; secrets do not. Reopening that file later and querying S3 fails with
-- "No credentials are provided": run this file again in every session that
-- reads S3 (`.read views.sql`, or `duckdb -init views.sql your.db`).
-- Do not make it PERSISTENT: DuckDB would resolve your credential chain now
-- and store the resulting keys on disk.
-- No credentials appear in this file by design. If the credential chain is not
-- available where you run this, replace the secret above with explicit keys:
--   CREATE OR REPLACE SECRET bintrail_s3_chain (
--     TYPE s3, KEY_ID '…', SECRET '…', REGION '…');

-- state_<schema>_<table>: each table's full contents as of the snapshot the
-- `current` pointer names, which is whichever one completed most recently.
--
-- These are the SNAPSHOT's rows, not the table's current state: changes after
-- the snapshot live in the `events` view.
-- To materialize a later point in time, use `bintrail reconstruct`. Folding
-- the deltas back onto a baseline is what that command does, and it is not
-- expressible as a view.
--
-- DECIMAL and NUMERIC columns are stored as text, so that a value MySQL can
-- hold is never rounded to fit a narrower type. The views below cast them
-- back to DECIMAL with the precision and scale the column was declared with,
-- so sum() and the rest work on them directly.
-- Columns wider than 38 digits have no DuckDB DECIMAL to be cast to, so they
-- stay text. They are named below. Cast them yourself when you need
-- arithmetic; DOUBLE works if an approximate result is acceptable.
-- Some files carry no column types, so their views cast nothing and every
-- decimal column in them reads as text. Those tables are named below. A
-- baseline older than this feature gains the casts when it is next taken or
-- refreshed; a PostgreSQL-source baseline stores all its values as text and
-- will not gain them. If a footer could not be read at all, the bintrail log
-- has the error.
-- Every table below has to still be in that snapshot. A table dropped at the
-- source leaves it, and DuckDB binds a view when it is created, so without
-- this the script would stop at that one view and never define the rest.
SET VARIABLE bintrail_missing_tables = (
  SELECT string_agg(t, ', ' ORDER BY t) FROM (VALUES
    ('Legacy-DB/Audit Log.parquet'),
    ('shop/order_items.parquet'),
    ('shop/orders.parquet'),
    ('shop_order/items.parquet')
  ) AS x(t)
  WHERE '/data/baselines/current/' || t NOT IN (SELECT file FROM glob('/data/baselines/current/' || '**/*.parquet')));
SET VARIABLE bintrail_tables_checked = (SELECT CASE WHEN getvariable('bintrail_missing_tables') IS NOT NULL
  THEN error('bintrail views: these tables are not in the newest snapshot any more: ' || getvariable('bintrail_missing_tables') ||
    '. Looked in ' || '/data/baselines/current/' ||
    '. If they were dropped or renamed, download this file again.') END);

-- state_legacy_db_audit_log: this file carries no column types, so nothing is cast; decimal columns read as text
CREATE OR REPLACE VIEW "state_legacy_db_audit_log" AS
  SELECT * FROM read_parquet('/data/baselines/current/Legacy-DB/Audit Log.parquet');
CREATE OR REPLACE VIEW "state_shop_order_items" AS
  SELECT * FROM read_parquet('/data/baselines/current/shop/order_items.parquet');
CREATE OR REPLACE VIEW "state_shop_orders" AS
  SELECT * REPLACE (CAST("total" AS DECIMAL(10,2)) AS "total", CAST("tax_rate" AS DECIMAL(6,4)) AS "tax_rate")
  FROM read_parquet('/data/baselines/current/shop/orders.parquet');
-- state_shop_order_items_2: weight is DECIMAL(65,30), wider than DuckDB's 38 digits (left as text)
CREATE OR REPLACE VIEW "state_shop_order_items_2" AS
  SELECT * FROM read_parquet('/data/baselines/current/shop_order/items.parquet');

-- events: every archived binlog event, across all archive sources.
--
-- union_by_name is required, not cosmetic: archives written before a column
-- existed simply lack it, and those files must read back with NULLs rather
-- than failing the whole scan. A column absent from EVERY archived file is
-- still an error here: drop it from the SELECT if you hit that on an old
-- archive. (The grouped form this file is not using pads it with NULL.)
--
-- COST: union_by_name makes DuckDB open one Parquet footer per archived file
-- to unify the schema, and a view re-binds on every statement, so the wait
-- before the first row grows with the archive.
--
-- SCOPE: these are the ARCHIVED events only. Partitions rotation has not
-- archived yet exist solely in the index, so the most recent window is
-- absent here and reads as if nothing happened.
-- Add a leg over the index by regenerating with --include-live:
--   bintrail views --index-dsn ... --include-live
CREATE OR REPLACE VIEW "events" AS
  SELECT
    "bintrail_id", "event_date", "event_hour",
    CAST("event_id" AS BIGINT) AS "event_id",
    "binlog_file",
    "start_pos",
    "end_pos",
    "event_timestamp",
    "gtid",
    "connection_id",
    "schema_name",
    "table_name",
    CAST("event_type" AS INTEGER) AS "event_type_code",
    CASE "event_type"
      WHEN 1 THEN 'INSERT'
      WHEN 2 THEN 'UPDATE'
      WHEN 3 THEN 'DELETE'
      ELSE CAST("event_type" AS VARCHAR)
    END AS "event_type",
    "pk_values",
    "changed_columns",
    "row_before",
    "row_after",
    CAST("schema_version" AS INTEGER) AS "schema_version",
    "query_text",
    "query_hash",
    "commit_ts_us",
    CASE WHEN "commit_ts_us" IS NULL THEN NULL
         ELSE make_timestamp(CAST("commit_ts_us" AS BIGINT)) END AS "commit_time"
  FROM read_parquet(
    [
      '/data/archives/bintrail_id=11111111-2222-3333-4444-555555555555/event_date=*/event_hour=*/*.parquet',
      's3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000/event_date=*/event_hour=*/*.parquet'
    ],
    hive_partitioning = true,
    union_by_name = true
  );

