-- DuckDB views over a bintrail archive layout.
-- Generated by bintrail v0.50.0 at 2026-05-01T12:00:00Z.
--
-- THIS FILE IS A SNAPSHOT OF THE LAYOUT, NOT A LIVE BINDING. The globs below
-- keep picking up newly rotated partitions on their own, but the baseline
-- state views point at ONE snapshot. Re-run `bintrail views` (or download the
-- file again from the console) after taking or refreshing a baseline, and
-- whenever archive sources are added or removed.
--
-- A daemon running `bintrail-console watch --baseline-refresh-interval`
-- publishes a new snapshot every interval, and nothing regenerates this file.
-- Any state view below stays bound to the snapshot it was generated against,
-- with no error and no warning: its rows just stop changing. Regenerate this
-- file on the same schedule that refresh runs on.
--
-- Nothing here writes: every view is a read over Parquet files you already own.
--
-- Archive sources (an archive registered with both a local path and an S3
-- location is listed by its S3 location, so those reads work from another
-- machine; a local path below means the registry holds no S3 location this
-- file can use):
--   /data/archives/bintrail_id=11111111-2222-3333-4444-555555555555
--   s3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000
-- Baseline snapshot:
--   s3://my-bucket/baselines/ at 2026-04-30T03:00:00Z (4 table(s))

-- Timestamps are recorded in UTC, and the archives carry the zone, so the
-- session's setting decides how they print and where date_trunc puts a day
-- boundary. Pinned to UTC here so the numbers match the console. Change it if
-- you would rather read in your own zone.
SET TimeZone = 'UTC';

-- S3 setup, mirroring what bintrail's own DuckDB sessions configure.
INSTALL httpfs; LOAD httpfs;
INSTALL aws; LOAD aws;
CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1');
-- This secret lives only in this DuckDB session. Views persist in a database
-- file; secrets do not. Reopening that file later and querying S3 fails with
-- "No credentials are provided": run this file again in every session that
-- reads S3 (`.read views.sql`, or `duckdb -init views.sql your.db`).
-- Do not make it PERSISTENT: DuckDB would resolve your credential chain now
-- and store the resulting keys on disk.
-- No credentials appear in this file by design. If the credential chain is not
-- available where you run this, replace the secret above with explicit keys:
--   CREATE OR REPLACE SECRET bintrail_s3_chain (
--     TYPE s3, KEY_ID '…', SECRET '…', REGION '…');

-- state_<schema>_<table>: each table's full contents as of the baseline snapshot.
--
-- These are the SNAPSHOT's rows, not the table's current state: changes after
-- the snapshot live in the `events` view.
-- To materialize a later point in time, use `bintrail reconstruct`. Folding
-- the deltas back onto a baseline is what that command does, and it is not
-- expressible as a view.
--
-- DECIMAL and NUMERIC columns are stored as text, so that a value MySQL can
-- hold is never rounded to fit a narrower type. The views below cast them
-- back to DECIMAL with the precision and scale the column was declared with,
-- so sum() and the rest work on them directly.
-- Columns wider than 38 digits have no DuckDB DECIMAL to be cast to, so they
-- stay text. They are named below. Cast them yourself when you need
-- arithmetic; DOUBLE works if an approximate result is acceptable.
-- Some files carry no column types, so their views cast nothing and every
-- decimal column in them reads as text. Those tables are named below. A
-- baseline older than this feature gains the casts when it is next taken or
-- refreshed; a PostgreSQL-source baseline stores all its values as text and
-- will not gain them. If a footer could not be read at all, the bintrail log
-- has the error.
-- state_legacy_db_audit_log: this file carries no column types, so nothing is cast; decimal columns read as text
CREATE OR REPLACE VIEW "state_legacy_db_audit_log" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/Legacy-DB/Audit Log.parquet');
CREATE OR REPLACE VIEW "state_shop_order_items" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/order_items.parquet');
CREATE OR REPLACE VIEW "state_shop_orders" AS
  SELECT * REPLACE (CAST("total" AS DECIMAL(10,2)) AS "total", CAST("tax_rate" AS DECIMAL(6,4)) AS "tax_rate")
  FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/orders.parquet');
-- state_shop_order_items_2: weight is DECIMAL(65,30), wider than DuckDB's 38 digits (left as text)
CREATE OR REPLACE VIEW "state_shop_order_items_2" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop_order/items.parquet');

-- Live index setup, for the hot leg of the events view.
-- FILL IN THE PASSWORD BELOW before running: this file is shareable and
-- carries none. Everything else is the index location, which is not secret.
-- Read-only: nothing in this file writes, and the ATTACH enforces it.
INSTALL mysql; LOAD mysql;
INSTALL icu; LOAD icu;
CREATE OR REPLACE SECRET "bintrail_index" (
    TYPE mysql,
    HOST 'index.example.com',
    PORT 3306,
    DATABASE 'bintrail_index',
    USER 'reader',
    PASSWORD ''  -- <- your index password
);
-- SHARED WITH CAPTURE: this attaches the index bintrail writes captured
-- events into, so a query over the events view reads the server capture is
-- writing to. The view cannot push your filter down to it (see COST below),
-- so every query is a full scan of binlog_events, and a big one competes with
-- capture for that server's disk and buffer pool. One measured run: an
-- analytical query over a 15 million row binlog_events, and capture on that
-- server stopped minutes later. An index write that runs past its timeout
-- ends the run in a standalone capture process (`bintrail stream`, `bintrail
-- up`, `bintrail-pg stream`), which then stays down until something restarts
-- it; `bintrail-console watch` restarts from its last checkpoint instead.
-- Capture is behind either way.
-- Two ways to keep it off capture: query `bintrail_live`."binlog_events"
-- directly with your own WHERE, which does reach the index, or point HOST
-- above at a read replica, at the cost of that replica's own lag on top of
-- capture lag.
ATTACH '' AS "bintrail_live" (TYPE mysql, SECRET "bintrail_index", READ_ONLY);

-- events: every binlog event, from the archives and from the index.
--
-- union_by_name is required, not cosmetic: archives written before a column
-- existed simply lack it, and those files must read back with NULLs rather
-- than failing the whole scan. A column absent from EVERY archived file is
-- still an error here: drop it from the SELECT if you hit that on an old
-- archive. (The grouped form this file is not using pads it with NULL.)
--
-- COST: union_by_name makes DuckDB open one Parquet footer per archived file
-- to unify the schema, and a view re-binds on every statement, so the wait
-- before the first row grows with the archive.
--
-- Two legs: the Parquet for everything rotation has archived, the index for
-- events it has not. A partition that has been archived but not yet dropped
-- exists on BOTH sides, so the index leg excludes any event_id the archives
-- already returned.
--
-- The ARCHIVES win that overlap, which is the one place this differs from
-- bintrail's own merge in Go. There the two copies of an event carry the same
-- fields and the winner is immaterial; here they do not. An archived row
-- knows its bintrail_id, event_date and event_hour from its path, and an
-- index row has to derive or forgo them. Letting the index win would
-- replace a known source with NULL for every event in the overlap, and a
-- WHERE bintrail_id = ... would then miss rows the archives hold.
--
-- Defined AFTER the ATTACH above, so an index this machine cannot reach
-- leaves this view undefined and the state_ views above already created.
-- Keeping them takes a session that outlives the error: `.read` this file
-- from an open DuckDB, or run `duckdb -init <this file> your.db` and then
-- reopen your.db. A bare `duckdb -init <this file>` exits on the error and
-- the in-memory database goes with it, so nothing is left.
-- Regenerating WITHOUT the live index gives an events view over the
-- archives alone, which needs nothing from the index.
--
-- It is deliberately not ALSO defined over the archives alone beforehand:
-- union_by_name opens one Parquet footer per archived file at CREATE VIEW
-- time, so a second definition pays that bind again in every generated
-- file, whether or not the index turns out to be reachable.
--
-- COST: a filter on this view does not become a filter on the index. The
-- index leg derives event_date and event_hour from event_timestamp, so a
-- predicate on them is applied after the rows are read, and the anti-join
-- needs every archived event_id regardless of what the query asked for.
-- Every query therefore streams the whole live binlog_events (row_before,
-- row_after and query_text included), and the archive scan behind the
-- anti-join is not pruned by your filter either.
-- For a narrow read of recent events, query "bintrail_live"."binlog_events" directly
-- with your own WHERE: that one does reach the index, which is indexed on
-- event_timestamp and on schema_name/table_name.
CREATE OR REPLACE VIEW "events" AS
  WITH cold AS (
    SELECT
      "bintrail_id", "event_date", "event_hour",
      CAST("event_id" AS BIGINT) AS "event_id",
      "binlog_file",
      "start_pos",
      "end_pos",
      "event_timestamp",
      "gtid",
      "connection_id",
      "schema_name",
      "table_name",
      CAST("event_type" AS INTEGER) AS "event_type_code",
      CASE "event_type"
      WHEN 1 THEN 'INSERT'
      WHEN 2 THEN 'UPDATE'
      WHEN 3 THEN 'DELETE'
      ELSE CAST("event_type" AS VARCHAR)
    END AS "event_type",
      "pk_values",
      "changed_columns",
      "row_before",
      "row_after",
      CAST("schema_version" AS INTEGER) AS "schema_version",
      "query_text",
      "query_hash",
      "commit_ts_us",
      CASE WHEN "commit_ts_us" IS NULL THEN NULL
           ELSE make_timestamp(CAST("commit_ts_us" AS BIGINT)) END AS "commit_time"
    FROM read_parquet(
      [
        '/data/archives/bintrail_id=11111111-2222-3333-4444-555555555555/event_date=*/event_hour=*/*.parquet',
        's3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000/event_date=*/event_hour=*/*.parquet'
      ],
      hive_partitioning = true,
      union_by_name = true
    )
  ), hot AS (
    SELECT
      '11111111-2222-3333-4444-555555555555' AS "bintrail_id",
      CAST(strftime("event_timestamp", '%Y-%m-%d') AS DATE) AS "event_date",
      strftime("event_timestamp", '%H') AS "event_hour",
      CAST("event_id" AS BIGINT) AS "event_id",
      NULL AS "binlog_file", -- not a column of this index's binlog_events
      NULL AS "start_pos", -- not a column of this index's binlog_events
      NULL AS "end_pos", -- not a column of this index's binlog_events
      "event_timestamp" AT TIME ZONE 'UTC' AS "event_timestamp",
      NULL AS "gtid", -- not a column of this index's binlog_events
      NULL AS "connection_id", -- not a column of this index's binlog_events
      "schema_name",
      "table_name",
      CAST("event_type" AS INTEGER) AS "event_type_code",
      CASE "event_type"
      WHEN 1 THEN 'INSERT'
      WHEN 2 THEN 'UPDATE'
      WHEN 3 THEN 'DELETE'
      ELSE CAST("event_type" AS VARCHAR)
    END AS "event_type",
      NULL AS "pk_values", -- not a column of this index's binlog_events
      NULL AS "changed_columns", -- not a column of this index's binlog_events
      NULL AS "row_before", -- not a column of this index's binlog_events
      NULL AS "row_after", -- not a column of this index's binlog_events
      NULL AS "schema_version", -- not a column of this index's binlog_events
      NULL AS "query_text", -- not a column of this index's binlog_events
      NULL AS "query_hash", -- not a column of this index's binlog_events
      NULL AS "commit_ts_us", -- not a column of this index's binlog_events
      NULL AS "commit_time"
    FROM "bintrail_live"."binlog_events"
  )
  SELECT * FROM cold
  UNION ALL BY NAME
  SELECT * FROM hot
   WHERE NOT EXISTS (SELECT 1 FROM cold WHERE cold.event_id = hot.event_id);

