package mcptools

import (
	"context"
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"

	"github.com/dbtrail/dbtrail/internal/audittest"
	"github.com/dbtrail/dbtrail/internal/parser"
)

// twoInsertRows mocks two indexed INSERTs on app.users so the recover tool
// renders a two-statement script through the real fetch → generate path.
func twoInsertRows(t *testing.T) (*sqlmock.Sqlmock, Config) {
	t.Helper()
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Close() })
	ts := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	rows := sqlmock.NewRows(recoverToolMockCols).
		AddRow(int64(2), "bin.000001", int64(80), int64(120), ts, nil, nil, "app", "users", int64(parser.EventInsert), "2",
			nil, nil, []byte(`{"id":2}`), int64(0), nil, nil, nil).
		AddRow(int64(1), "bin.000001", int64(4), int64(40), ts, nil, nil, "app", "users", int64(parser.EventInsert), "1",
			nil, nil, []byte(`{"id":1}`), int64(0), nil, nil, nil)
	mock.ExpectQuery("FROM binlog_events").WillReturnRows(rows)
	// The #1616 cascade probe runs after generation; an index without the
	// fk_constraints table answers "no cascade" in one query.
	mock.ExpectQuery("information_schema.TABLES").WillReturnRows(sqlmock.NewRows([]string{"e"}).AddRow(false))
	return &mock, newRecoverToolTarget(db, 0)
}

// The whole script is plain SQL, exactly as before #1438; a chunk or a summary
// is a JSON envelope, so a client reading FIELDS can tell one from the other.
func TestRecoverTool_envelopeOnlyForChunksAndSummaries(t *testing.T) {
	ctx := context.Background()

	_, cfg := twoInsertRows(t)
	res, _, _ := MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users"})
	if res.IsError {
		t.Fatalf("whole: %s", resultText(res))
	}
	whole := resultText(res)
	if !strings.HasPrefix(whole, "-- Generated by bintrail recover") || strings.HasPrefix(whole, "{") {
		t.Fatalf("a whole script must come back as plain SQL, got: %.80q", whole)
	}

	_, cfg = twoInsertRows(t)
	res, _, _ = MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users", SQLOffset: 0, SQLLimit: 1})
	if res.IsError {
		t.Fatalf("chunk: %s", resultText(res))
	}
	var chunk recoverResult
	if err := json.Unmarshal([]byte(resultText(res)), &chunk); err != nil {
		t.Fatalf("a chunk must come back as a JSON envelope, got %.80q: %v", resultText(res), err)
	}
	if chunk.SQLFrom != 1 || chunk.SQLTo != 1 || !chunk.SQLMore || chunk.NextSQLOffset != 1 || chunk.StatementCount != 2 {
		t.Fatalf("chunk envelope: %+v", chunk)
	}
	if strings.Contains(chunk.SQL, "COMMIT;") {
		t.Error("the first of two chunks carries the COMMIT trailer")
	}

	_, cfg = twoInsertRows(t)
	res, _, _ = MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users", SummaryOnly: true})
	var sum recoverResult
	if err := json.Unmarshal([]byte(resultText(res)), &sum); err != nil {
		t.Fatalf("a summary must come back as a JSON envelope: %v", err)
	}
	if sum.SQL != "" || sum.StatementCount != 2 || sum.ScriptID == "" {
		t.Fatalf("summary envelope: %+v", sum)
	}
}

// The advisories a whole script carries as SQL comments ride the envelope's
// warnings field when the script itself is not carried: truncation is the
// case most likely to accompany a script too large to return inline.
func TestRecoverTool_summaryCarriesTheWarnings(t *testing.T) {
	_, cfg := twoInsertRows(t)
	res, _, _ := MakeRecoverTool(cfg)(context.Background(), nil, RecoverArgs{Schema: "app", Table: "users", Limit: 2, SummaryOnly: true})
	if res.IsError {
		t.Fatal(resultText(res))
	}
	var sum recoverResult
	if err := json.Unmarshal([]byte(resultText(res)), &sum); err != nil {
		t.Fatal(err)
	}
	if len(sum.Warnings) != 1 || !strings.Contains(sum.Warnings[0], "truncated at 2 rows") {
		t.Fatalf("the truncation warning did not reach the summary: %+v", sum.Warnings)
	}
	for _, w := range sum.Warnings {
		if strings.Contains(w, "--") {
			t.Errorf("a warning names a CLI flag: %s", w)
		}
	}

	// And the whole-script text still carries it as a comment, unchanged.
	_, cfg = twoInsertRows(t)
	res, _, _ = MakeRecoverTool(cfg)(context.Background(), nil, RecoverArgs{Schema: "app", Table: "users", Limit: 2})
	if !strings.Contains(resultText(res), "-- Warning: results truncated at 2 rows") {
		t.Errorf("the whole script lost its truncation comment: %.200q", resultText(res))
	}
}

// The audit record follows the bytes: a summary serves none and records
// nothing; a chunk records its range and script id; a whole return records
// without a range.
func TestRecoverTool_auditFollowsTheBytes(t *testing.T) {
	rec := audittest.Install(t)
	ctx := context.Background()

	_, cfg := twoInsertRows(t)
	MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users", SummaryOnly: true})
	if n := len(rec.Events()); n != 0 {
		t.Fatalf("summary_only recorded %d audit event(s); it serves no row data", n)
	}

	_, cfg = twoInsertRows(t)
	// Offset 0 of 2: From, To and n differ, so the range cannot pass by
	// coincidence with the wrong field in a slot.
	MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users", SQLOffset: 0, SQLLimit: 1})
	events := rec.Events()
	if len(events) != 1 || events[0].Action != "recover.generate" {
		t.Fatalf("a chunk fetch recorded %+v, want one recover.generate", events)
	}
	if got := events[0].Detail["chunk"]; got != "statements 1-1 of 2" {
		t.Errorf("chunk range in the audit detail = %q", got)
	}
	if events[0].Detail["script_id"] == "" {
		t.Error("a chunk record carries no script id")
	}

	_, cfg = twoInsertRows(t)
	MakeRecoverTool(cfg)(ctx, nil, RecoverArgs{Schema: "app", Table: "users"})
	events = rec.Events()
	if len(events) != 2 {
		t.Fatalf("a whole return recorded %d event(s) in total, want 2", len(events))
	}
	if _, ok := events[1].Detail["chunk"]; ok {
		t.Error("a whole-script return carries a chunk range")
	}
}
