package mcptools

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// InlineScriptBytes is the largest reversal script the recover tools return in
// one response. Past it the response carries the summary and says how to fetch
// the script in pieces, because an MCP client caps tool-result size: a script
// that outgrows the cap is refused or truncated by the client, and the operator
// loses exactly the artifact the call exists to produce (#1438). 64 KiB is
// under every client limit observed and above the scripts a routine recovery
// produces, so the one-call ergonomics survive for the common case.
const InlineScriptBytes = 64 << 10

// generatedAtPrefix marks the one line of a reversal script that changes
// between two otherwise identical builds. scriptFingerprint drops it; see
// there for why.
const generatedAtPrefix = "-- Generated by bintrail recover at "

// scriptDelivery is what one response carries of a built script: either the
// whole thing, one statement-aligned chunk of it, or nothing but the counts.
//
// Chunks are stateless REBUILDS — nothing is cached between calls — so two
// chunks can come from two different builds: an event indexed in between, a
// newer baseline published, archives rotated. Concatenating those yields a
// script that never existed, undetectably. ScriptID is how a client detects
// it: a changed value means the build moved and the fetch must restart at
// offset 0.
type scriptDelivery struct {
	SQL         string // the chunk (or the whole script); empty when only counts are carried
	ScriptID    string
	ScriptBytes int // the WHOLE script's size, not this chunk's
	// From and To are the 1-based inclusive statement range carried in SQL;
	// both 0 when no script bytes are carried.
	From, To   int
	More       bool
	NextOffset int
	Note       string
	// Served reports whether script bytes are in this response. It is the audit
	// gate: a summary carries counts, which is a metadata read, and
	// ext/audit.go deliberately leaves those out.
	Served bool
	// Chunked reports an explicitly paginated request, so a reader of the audit
	// record can tell one chunk of a recovery from a whole script without
	// arithmetic.
	Chunked bool
}

// scriptFingerprint identifies a BUILD of a script, ignoring the one line that
// differs between two builds of identical content: the generator stamps the
// current time into its preamble, so hashing the raw text would make every
// fingerprint unique and the cross-chunk check useless. Everything else is
// deliberately inside the hash, caveats included — a caveat that appears
// between two chunk fetches means the coverage changed, which is exactly the
// case a client must not concatenate across.
func scriptFingerprint(text string) string {
	h := sha256.New()
	for line := range strings.SplitSeq(text, "\n") {
		if strings.HasPrefix(line, generatedAtPrefix) {
			continue
		}
		h.Write([]byte(line))
		h.Write([]byte("\n"))
	}
	return hex.EncodeToString(h.Sum(nil))[:12]
}

// deliverScript decides what this response carries of text, whose statements
// end at the byte offsets in ends (recovery.GenerateSQLFromRowsIndexed /
// cascaderecover.EmitSQLIndexed).
//
// Cutting on those recorded offsets rather than scanning the rendered text is
// the whole point: a `;` and a newline are both ordinary characters inside a
// captured value, so a scanner can cut a statement in half and the halves
// still look like SQL.
//
// The preamble precedes the first statement's end and the COMMIT / FK-checks
// trailer follows the last one, so the framing lands in the first and last
// chunk exactly once, with no special-casing: concatenating every chunk in
// order reproduces text byte for byte.
func deliverScript(text string, ends []int, summaryOnly bool, offset, limit int) (scriptDelivery, error) {
	total := len(ends)
	d := scriptDelivery{
		ScriptID:    scriptFingerprint(text),
		ScriptBytes: len(text),
	}
	explicit := offset > 0 || limit > 0

	if offset < 0 || limit < 0 {
		return d, fmt.Errorf("sql_offset and sql_limit count statements and cannot be negative (got sql_offset: %d, sql_limit: %d)", offset, limit)
	}
	if explicit && total == 0 {
		return d, fmt.Errorf("this recovery generated no statements, so there is nothing to page through; call again without sql_offset/sql_limit")
	}
	if offset >= total && total > 0 {
		return d, fmt.Errorf("sql_offset %d is past the end of the script: it has %d statement(s), so the last valid sql_offset is %d", offset, total, total-1)
	}

	if summaryOnly {
		d.Note = fmt.Sprintf("the script was built but not returned (summary_only). %d statement(s), %d bytes, script id %s. "+
			"Fetch it with sql_offset (0-based statement index) and sql_limit, or call again without summary_only for the whole script.",
			total, len(text), d.ScriptID)
		return d, nil
	}

	// A statement count of zero means the generator wrote a comment instead of
	// a script ("no events matched"); there is nothing to page and the text is
	// tiny, so it goes back whole.
	if total == 0 {
		d.SQL, d.Served = text, true
		return d, nil
	}

	if !explicit && len(text) <= InlineScriptBytes {
		d.SQL, d.Served = text, true
		d.From, d.To = 1, total
		return d, nil
	}
	if !explicit {
		d.Note = fmt.Sprintf("the script is %d bytes, over the %d-byte limit for one response, so it was NOT returned here "+
			"(returning it would be refused or truncated by the client). It has %d statement(s), script id %s. "+
			"Fetch it in order with sql_offset (0-based statement index) and sql_limit, checking script_id on every chunk: "+
			"a different value means the underlying events moved and the fetch must restart at sql_offset 0. "+
			"`bintrail recover-cascade` from the CLI writes the whole script to a file in one go.",
			len(text), InlineScriptBytes, total, d.ScriptID)
		return d, nil
	}

	// How many statements fit the response cap from here. At least one, always:
	// a single statement larger than the cap is still the only way to ever see
	// it, and the note says the response is over the usual size.
	start := 0
	if offset > 0 {
		start = ends[offset-1]
	}
	fits := 0
	for i := offset; i < total; i++ {
		if ends[i]-start > InlineScriptBytes && fits > 0 {
			break
		}
		fits++
	}
	want := limit
	if want == 0 || want > fits {
		want = fits
	}
	last := offset + want // exclusive statement index
	end := len(text)
	if last < total {
		end = ends[last-1]
	}

	d.SQL, d.Served, d.Chunked = text[start:end], true, true
	d.From, d.To = offset+1, last
	d.More = last < total
	if d.More {
		d.NextOffset = last
	}
	d.Note = chunkNote(offset, last, total, limit, want, d.ScriptID)
	return d, nil
}

// chunkNote is the human half of the pagination contract: which statements
// these bytes are, how many there are in total, and what to ask for next. A
// client that never reads a field still cannot mistake a chunk for a whole
// script, which is the failure the size cap exists to prevent.
func chunkNote(offset, last, total, askedLimit, gave int, id string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "statements %d-%d of %d (script id %s)", offset+1, last, total, id)
	if i, n, ok := chunkOrdinal(offset, gave, total); ok {
		fmt.Fprintf(&b, ", chunk %d of %d at this sql_limit", i, n)
	}
	if askedLimit > 0 && gave < askedLimit {
		fmt.Fprintf(&b, ". sql_limit %d was reduced to %d so the response fits its size limit; nothing was dropped",
			askedLimit, gave)
	}
	if last < total {
		fmt.Fprintf(&b, ". Fetch the next with sql_offset: %d", last)
		b.WriteString(". Concatenate the chunks in order to get the script exactly as the CLI writes it; " +
			"the BEGIN/COMMIT framing and the preamble are in the first and last chunk, so no chunk is runnable alone. " +
			"Re-check script_id on every chunk: a different value means the build moved and the fetch must restart at sql_offset 0")
	} else {
		b.WriteString(". This is the last chunk")
	}
	return b.String()
}

// chunkOrdinal is the "chunk i of n" framing, reported only where it is true.
// It is well defined solely when the pages are uniform, and a client is free
// to change sql_limit between calls: with a first page of 300 and a second of
// 50 there is no honest i of n, so none is offered rather than one computed
// from an assumption the caller never made.
func chunkOrdinal(offset, gave, total int) (int, int, bool) {
	if gave <= 0 || offset%gave != 0 {
		return 0, 0, false
	}
	return offset/gave + 1, (total + gave - 1) / gave, true
}
