package mcptools

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
)

// InlineScriptBytes is the largest reversal script the recover tools return in
// one response. Past it the response carries the summary and says how to fetch
// the script in pieces, because an MCP client caps tool-result size: a script
// that outgrows the cap is refused or truncated by the client, and the operator
// loses exactly the artifact the call exists to produce (#1438). 64 KiB is
// under every client limit observed and above the scripts a routine recovery
// produces, so the one-call ergonomics survive for the common case.
const InlineScriptBytes = 64 << 10

// generatedAtPrefix marks the one line of a reversal script that changes
// between two otherwise identical builds. scriptFingerprint drops it; see
// there for why.
const generatedAtPrefix = "-- Generated by bintrail recover at "

// scriptDelivery is what one response carries of a built script: either the
// whole thing, one statement-aligned chunk of it, or nothing but the counts.
//
// Chunks are stateless REBUILDS — nothing is cached between calls — so two
// chunks can come from two different builds: an event indexed in between, a
// newer baseline published, archives rotated. Concatenating those yields a
// script that never existed, undetectably. ScriptID is how a client detects
// it: a changed value means the build moved and the fetch must restart at
// offset 0.
type scriptDelivery struct {
	SQL         string // the chunk (or the whole script); empty when only counts are carried
	ScriptID    string
	ScriptBytes int // the WHOLE script's size, not this chunk's
	// From and To are the 1-based inclusive statement range carried in SQL;
	// both 0 when no script bytes are carried.
	From, To   int
	More       bool
	NextOffset int
	Note       string
	// Served reports whether script bytes are in this response. It is the audit
	// gate: a summary carries counts, which is a metadata read, and
	// ext/audit.go deliberately leaves those out.
	Served bool
	// Chunked reports an explicitly paginated request, so a reader of the audit
	// record can tell one chunk of a recovery from a whole script without
	// arithmetic.
	Chunked bool
}

// scriptFingerprint identifies a BUILD of a script, ignoring the one line that
// differs between two builds of identical content: the generator stamps the
// current time into its preamble, so hashing the raw text would make every
// fingerprint unique and the cross-chunk check useless. Everything else is
// deliberately inside the hash, caveats included — a caveat that appears
// between two chunk fetches means the coverage changed, which is exactly the
// case a client must not concatenate across.
func scriptFingerprint(text string) string {
	h := sha256.New()
	skipped := false
	for line := range strings.SplitSeq(text, "\n") {
		// Only the FIRST such line is the generator's stamp; a captured value
		// that happens to start a line with the same prefix (PostgreSQL
		// literals carry raw newlines) is content and stays in the hash.
		if !skipped && strings.HasPrefix(line, generatedAtPrefix) {
			skipped = true
			continue
		}
		h.Write([]byte(line))
		h.Write([]byte("\n"))
	}
	return hex.EncodeToString(h.Sum(nil))[:12]
}

// deliverScript decides what this response carries of text, whose statements
// end at the byte offsets in ends (recovery.GenerateSQLFromRowsIndexed /
// cascaderecover.EmitSQLIndexed).
//
// Cutting on those recorded offsets rather than scanning the rendered text is
// the whole point: a `;` and a newline are both ordinary characters inside a
// captured value, so a scanner can cut a statement in half and the halves
// still look like SQL.
//
// The preamble precedes the first statement's end and the COMMIT / FK-checks
// trailer follows the last one, so the framing lands in the first and last
// chunk exactly once, with no special-casing: concatenating every chunk in
// order reproduces text byte for byte.
//
// cli names the CLI command that writes this same script whole (`bintrail
// recover` or `bintrail recover-cascade`): deliverScript serves both tools and
// the withhold note must send each client to ITS command, not the wider one.
//
// wholeIsBare says how a WHOLE script ships: recover returns it as bare text
// (one JSON escaping layer, the protocol's own), recover_cascade inside its
// JSON envelope (two layers: the envelope string is itself a protocol string).
// A chunk or a summary rides the envelope on both tools, so those paths are
// always sized with two layers; sizing with one measured a layer below the
// wire and let a quote-heavy page ship at twice the cap.
func deliverScript(cli, text string, ends []int, wholeIsBare, summaryOnly bool, offset, limit int) (scriptDelivery, error) {
	total := len(ends)
	d := scriptDelivery{
		ScriptID:    scriptFingerprint(text),
		ScriptBytes: len(text),
	}
	explicit := offset > 0 || limit > 0

	// Fail closed on offsets that do not sit on a statement boundary. The
	// emitters record them off a counting writer, but a rebase that forgets the
	// preamble (or drops a byte) lands every cut mid-statement while the
	// concatenation of the chunks STILL equals the script — any increasing
	// offset list reassembles. This is the check that sees it, and it refuses
	// rather than serving a chunk that starts inside a comment or a value.
	// Only a cut depends on the offsets: a whole return or a summary is served
	// regardless, so a bad list never takes the non-chunked paths down too.
	if explicit {
		if err := checkStatementEnds(text, ends); err != nil {
			return d, err
		}
	}

	if offset < 0 || limit < 0 {
		return d, fmt.Errorf("sql_offset and sql_limit count statements and cannot be negative (got sql_offset: %d, sql_limit: %d)", offset, limit)
	}
	if explicit && total == 0 {
		return d, fmt.Errorf("this recovery generated no statements, so there is nothing to page through; call again without sql_offset/sql_limit")
	}
	if offset >= total && total > 0 {
		// The id rides the refusal: a script that SHRANK between two chunk
		// calls lands here, and this is the client's first chance to see that
		// the build moved rather than that it miscounted.
		return d, fmt.Errorf("sql_offset %d is past the end of the script: it has %d statement(s), so the last valid sql_offset is %d (script id %s; if your earlier chunks carry a different id, the build moved and the fetch must restart at sql_offset 0)", offset, total, total-1, d.ScriptID)
	}

	if summaryOnly {
		d.Note = fmt.Sprintf("the script was built but not returned (summary_only). %d statement(s), %d bytes, script id %s. "+
			"Fetch it with sql_offset (0-based statement index) and sql_limit, or call again without summary_only for the whole script.",
			total, len(text), d.ScriptID)
		return d, nil
	}

	// A statement count of zero means the generator wrote a comment instead of
	// a script ("no events matched"); there is nothing to page and the text is
	// tiny, so it goes back whole.
	if total == 0 {
		d.SQL, d.Served = text, true
		return d, nil
	}

	wholeLayers := envelopeLayers
	if wholeIsBare {
		wholeLayers = 1
	}
	// len(text) first: wireLen is never smaller than the raw size, and a
	// script over the cap raw must not be fully escaped (up to several times
	// its size) only to be withheld.
	if !explicit && len(text) <= InlineScriptBytes && wireLen(text, wholeLayers) <= InlineScriptBytes {
		d.SQL, d.Served = text, true
		d.From, d.To = 1, total
		return d, nil
	}
	if !explicit {
		// The figure is the WIRE size, the one the decision was made on: a raw
		// count smaller than the limit it claims to exceed sends an operator
		// hunting an arithmetic error instead of the escaping.
		d.Note = fmt.Sprintf("the script is %d bytes on the wire, over the %d-byte limit for one response, so it was NOT returned here "+
			"(returning it would be refused or truncated by the client). It has %d statement(s), script id %s. "+
			"Fetch it in order with sql_offset (0-based statement index) and sql_limit, checking script_id on every chunk: "+
			"a different value means the underlying events moved and the fetch must restart at sql_offset 0. "+
			"`%s` from the CLI writes the whole script to a file in one go.",
			wireLen(text, wholeLayers), InlineScriptBytes, total, d.ScriptID, cli)
		return d, nil
	}

	// How many statements fit the response cap from here, measured as the
	// bytes that CROSS THE WIRE (the chunk rides a JSON string, and escaping
	// grows it: every newline and backslash doubles, `<` becomes six bytes),
	// with the trailer counted on the last page since it rides that chunk. At
	// least one statement, always: a single statement larger than the cap is
	// still the only way to ever see it, and the note then says the response
	// is over the usual size (see the oversized clause below).
	start := 0
	if offset > 0 {
		start = ends[offset-1]
	}
	fits, acc, prev := 0, 0, start
	for i := offset; i < total; i++ {
		segEnd := ends[i]
		if i == total-1 {
			segEnd = len(text)
		}
		acc += wireLen(text[prev:segEnd], envelopeLayers)
		if acc > InlineScriptBytes && fits > 0 {
			break
		}
		fits++
		prev = segEnd
	}
	want := limit
	if want == 0 || want > fits {
		want = fits
	}
	last := offset + want // exclusive statement index
	end := len(text)
	if last < total {
		end = ends[last-1]
	}

	d.SQL, d.Served, d.Chunked = text[start:end], true, true
	d.From, d.To = offset+1, last
	d.More = last < total
	if d.More {
		d.NextOffset = last
	}
	d.Note = chunkNote(offset, last, total, limit, want, d.ScriptID)
	// Only a lone statement can be over the cap here: the fits loop measures
	// every page on the wire, trailer included, and stops before overflowing
	// unless the first statement alone already does.
	if wl := wireLen(d.SQL, envelopeLayers); wl > InlineScriptBytes {
		d.Note += fmt.Sprintf(". This chunk is %d bytes on the wire, over the usual %d-byte response size: one statement (with the closing lines, on the last chunk) cannot be split further",
			wl, InlineScriptBytes)
	}
	return d, nil
}

// envelopeLayers is how many times a chunk's bytes are JSON-escaped before
// they reach the client: once into the tool's JSON envelope (`sql` field),
// and once more when that envelope rides the protocol's text content, which
// is itself a JSON string. A whole recover script skips the envelope.
const envelopeLayers = 2

// wireLen is the size of s after `layers` JSON escapings: the escaped string
// body, without the quotes. It is what a client's result cap actually sees,
// and it can be well over len(s) for HTML-heavy or newline-heavy rows (a
// newline is 3 bytes after two layers, a quote 4, `<` 7). Escaping is per
// character at every layer, so the wire length of a concatenation is the sum
// of its parts, which is what lets the fits loop accumulate per statement.
func wireLen(s string, layers int) int {
	cur := s
	for range layers {
		b, err := json.Marshal(cur)
		if err != nil {
			return len(s) // unreachable for a Go string; never smaller than the raw size
		}
		cur = string(b[1 : len(b)-1])
	}
	return len(cur)
}

// checkStatementEnds verifies that every recorded statement end sits just
// past a `;` and its newline, strictly increasing and inside text. The
// emitters guarantee that shape (every statement is written as stmt + ";\n"),
// so a violation means the offsets were rebased wrong, and a chunk cut on
// them would start mid-statement.
func checkStatementEnds(text string, ends []int) error {
	prev := 0
	for i, e := range ends {
		if e <= prev || e > len(text) || e < 2 || text[e-1] != '\n' || text[e-2] != ';' {
			return fmt.Errorf("internal error: statement offset %d of %d (byte %d) does not end a statement; refusing to cut the script there. Call again without sql_offset/sql_limit, or write it whole from the CLI, and report this", i+1, len(ends), e)
		}
		prev = e
	}
	return nil
}

// chunkNote is the human half of the pagination contract: which statements
// these bytes are, how many there are in total, and what to ask for next. A
// client that never reads a field still cannot mistake a chunk for a whole
// script, which is the failure the size cap exists to prevent.
func chunkNote(offset, last, total, askedLimit, gave int, id string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "statements %d-%d of %d (script id %s)", offset+1, last, total, id)
	if i, n, ok := chunkOrdinal(offset, askedLimit, gave, last, total); ok {
		fmt.Fprintf(&b, ", chunk %d of %d at this sql_limit", i, n)
	}
	// "Reduced" only when the size cap cut the page short: fewer than asked
	// AND fewer than remained. On the last chunk gave < askedLimit merely
	// because the script ended, and saying the cap did it would send a client
	// looking for bytes that never existed.
	if avail := total - offset; askedLimit > 0 && gave < min(askedLimit, avail) {
		fmt.Fprintf(&b, ". sql_limit %d was reduced to %d so the response fits its size limit; nothing was dropped",
			askedLimit, gave)
	}
	if last < total {
		fmt.Fprintf(&b, ". Fetch the next with sql_offset: %d", last)
		b.WriteString(". Concatenate the chunks in order to get the script exactly as this tool returns it whole; " +
			"the preamble is in the first chunk and the closing lines in the last, so no chunk is runnable alone. " +
			"Re-check script_id on every chunk: a different value means the build moved and the fetch must restart at sql_offset 0")
	} else {
		b.WriteString(". This is the last chunk")
	}
	return b.String()
}

// chunkOrdinal is the "chunk i of n" framing, reported only where it is true.
// It is well defined solely when the pages are uniform at the ASKED limit: a
// client is free to change sql_limit between calls (a first page of 300 and a
// second of 50 have no honest i of n), and a page the size cap cut short
// breaks the grid for every later offset. Dividing by what was GIVEN instead
// produced "chunk 6 of 6" on the third and last of three pages, whenever the
// short tail happened to divide the offset. Once a reduction happens
// mid-walk the ordinal simply disappears for the rest of the fetch; the
// statement range carries the progress on its own.
func chunkOrdinal(offset, askedLimit, gave, last, total int) (int, int, bool) {
	if askedLimit <= 0 || offset%askedLimit != 0 {
		return 0, 0, false
	}
	if gave != askedLimit && last != total {
		return 0, 0, false
	}
	return offset/askedLimit + 1, (total + askedLimit - 1) / askedLimit, true
}
