package mcptools

import (
	"strings"
	"testing"
)

// buildFixture renders a script-shaped string with a preamble, `n` statements
// and a trailer, and returns it with the byte offset just past each statement
// — the shape recovery.GenerateSQLFromRowsIndexed produces.
//
// One statement carries a value with an embedded newline AND a semicolon,
// because that is the whole reason the offsets are recorded rather than
// scanned: both characters are ordinary inside a captured VARCHAR, so a
// scanner cutting on ";\n" cuts that statement in half and both halves still
// look like SQL.
const cascadeCLI = "bintrail recover-cascade"

func buildFixture(n int) (string, []int) {
	var b strings.Builder
	b.WriteString("-- Generated by bintrail recover at 2026-09-02 10:00:00 UTC\n")
	b.WriteString("-- Events to reverse: 3\n\nBEGIN;\n")
	ends := make([]int, 0, n)
	for i := range n {
		if i == 1 {
			b.WriteString("UPDATE `t` SET `note` = 'line one;\nline two' WHERE `id` = 2;\n")
		} else {
			b.WriteString("DELETE FROM `t` WHERE `id` = 1;\n")
		}
		ends = append(ends, b.Len())
	}
	b.WriteString("\nCOMMIT;\n")
	return b.String(), ends
}

// TestDeliverScript_chunksConcatenateIntoTheScript is the one assertion that
// catches every offset bug at once: over a spread of chunk sizes, the pieces
// joined in order must be the script byte for byte. It also pins the framing
// promise — the preamble rides the first chunk and the COMMIT trailer the last,
// with no chunk carrying either twice.
func TestDeliverScript_chunksConcatenateIntoTheScript(t *testing.T) {
	const n = 9
	text, ends := buildFixture(n)

	for _, size := range []int{1, 2, 3, 7, n - 1, n} {
		var got strings.Builder
		chunks, offset := 0, 0
		for {
			d, err := deliverScript(cascadeCLI, text, ends, false, offset, size)
			if err != nil {
				t.Fatalf("size %d, offset %d: %v", size, offset, err)
			}
			if !d.Served {
				t.Fatalf("size %d, offset %d: no bytes served", size, offset)
			}
			got.WriteString(d.SQL)
			chunks++
			if !d.More {
				if d.From > 1 && !strings.Contains(d.SQL, "COMMIT;") {
					t.Errorf("size %d: the last chunk does not carry the COMMIT trailer", size)
				}
				break
			}
			if d.NextOffset <= offset {
				t.Fatalf("size %d: next offset %d did not advance past %d", size, d.NextOffset, offset)
			}
			offset = d.NextOffset
			if chunks > n+2 {
				t.Fatalf("size %d: chunking did not terminate", size)
			}
		}
		if got.String() != text {
			t.Errorf("size %d: the concatenated chunks are not the script.\n got %q\nwant %q", size, got.String(), text)
		}
		if want := (n + size - 1) / size; chunks != want {
			t.Errorf("size %d: %d chunk(s), want %d", size, chunks, want)
		}
	}
}

// A statement whose value holds a newline and a semicolon must never be cut.
// This is what discriminates recorded offsets from a scanner: a refactor to
// split on ";\n" passes the concatenation test above — ANY increasing set of
// offsets concatenates back into the text, since each chunk runs from the
// previous boundary to the next — and fails only here.
//
// Nine statements, walked one at a time, so a boundary inside the embedded
// value is reachable as a chunk END and not merely as a start. With three the
// bogus boundary only ever falls in the final chunk, which runs to the end of
// the text regardless, and the scanner survives.
func TestDeliverScript_neverCutsInsideAValue(t *testing.T) {
	const n = 9
	text, ends := buildFixture(n)
	for offset := range n {
		d, err := deliverScript(cascadeCLI, text, ends, false, offset, 1)
		if err != nil {
			t.Fatal(err)
		}
		// Every chunk holds whole statements, so the embedded value is intact
		// wherever it appears: never a chunk that starts or ends mid-literal.
		if strings.Count(d.SQL, "'")%2 != 0 {
			t.Errorf("offset %d cut inside a string literal (odd number of quotes):\n%s", offset, d.SQL)
		}
		if strings.Contains(d.SQL, "line one;") != strings.Contains(d.SQL, "line two") {
			t.Errorf("offset %d split the multi-line value across chunks:\n%s", offset, d.SQL)
		}
	}
}

// summary_only builds the script and returns none of it: the counts and the
// size answer "how big is this" without spending the response on bytes the
// caller may not want. No script bytes means no audit record, which is why
// Served has to be false here.
func TestDeliverScript_summaryCarriesNoBytes(t *testing.T) {
	text, ends := buildFixture(4)
	d, err := deliverScript(cascadeCLI, text, ends, true, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.SQL != "" || d.Served {
		t.Fatalf("summary_only served bytes: served=%v len=%d", d.Served, len(d.SQL))
	}
	if d.ScriptBytes != len(text) || d.ScriptID == "" {
		t.Fatalf("summary lost the size or the id: %+v", d)
	}
	if !strings.Contains(d.Note, "sql_offset") {
		t.Errorf("the summary does not say how to fetch the script: %q", d.Note)
	}
}

// The size cap decides the DEFAULT only: a small script still comes back whole
// in one call, and a large one is withheld with instructions rather than
// truncated. A truncated script that looks complete is the failure this
// exists to prevent.
func TestDeliverScript_sizeCapWithholdsRatherThanTruncates(t *testing.T) {
	small, smallEnds := buildFixture(3)
	d, err := deliverScript(cascadeCLI, small, smallEnds, false, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.SQL != small || !d.Served || d.Chunked {
		t.Fatalf("a small script must come back whole and unchunked: served=%v chunked=%v", d.Served, d.Chunked)
	}

	big, bigEnds := buildFixture(4000)
	if len(big) <= InlineScriptBytes {
		t.Fatalf("fixture is only %d bytes; it must exceed the %d-byte cap to test it", len(big), InlineScriptBytes)
	}
	d, err = deliverScript(cascadeCLI, big, bigEnds, false, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.SQL != "" || d.Served {
		t.Fatalf("an oversized script was returned inline (%d bytes); the client would refuse or truncate it", len(d.SQL))
	}
	if !strings.Contains(d.Note, "sql_offset") || !strings.Contains(d.Note, "script_id") {
		t.Errorf("the withheld-script note must say how to fetch it and to check the id: %q", d.Note)
	}
}

// An explicit sql_limit that would overflow the response is REDUCED, and the
// response says so with the next offset. Silently returning fewer statements
// than asked, with no marker, is the truncation the issue bans.
func TestDeliverScript_oversizedRequestIsReducedNotSilent(t *testing.T) {
	big, ends := buildFixture(4000)
	d, err := deliverScript(cascadeCLI, big, ends, false, 0, 4000)
	if err != nil {
		t.Fatal(err)
	}
	if !d.Served || d.To == 4000 {
		t.Fatalf("a 4000-statement request over the cap was served whole: to=%d", d.To)
	}
	if len(d.SQL) > InlineScriptBytes+len(big)/4000 {
		t.Errorf("the chunk is %d bytes, over the %d-byte cap", len(d.SQL), InlineScriptBytes)
	}
	if !d.More || d.NextOffset != d.To {
		t.Fatalf("a reduced chunk must report more and the next offset: %+v", d)
	}
	if !strings.Contains(d.Note, "reduced") || !strings.Contains(d.Note, "nothing was dropped") {
		t.Errorf("the reduction is not stated in the note: %q", d.Note)
	}
}

// A single statement larger than the cap is still returned: refusing it would
// make those bytes unreachable from this surface, and the response is honest
// about being one statement.
func TestDeliverScript_oneOversizedStatementStillComesBack(t *testing.T) {
	huge := "BEGIN;\nUPDATE `t` SET `blob` = '" + strings.Repeat("x", InlineScriptBytes*2) + "' WHERE `id` = 1;\n"
	ends := []int{len(huge)}
	huge += "\nCOMMIT;\n"
	d, err := deliverScript(cascadeCLI, huge, ends, false, 0, 1)
	if err != nil {
		t.Fatal(err)
	}
	if !d.Served || d.From != 1 || d.To != 1 || d.More {
		t.Fatalf("the single statement was not served whole: %+v", d)
	}
	if d.SQL != huge {
		t.Error("the only chunk must carry the whole script, trailer included")
	}
}

// Offsets are validated against the script's real statement count, so a client
// that pages past the end learns the count instead of receiving an empty chunk
// it would read as "the script ended here".
func TestDeliverScript_rejectsOffsetsOutsideTheScript(t *testing.T) {
	text, ends := buildFixture(3)
	for _, tc := range []struct {
		name          string
		offset, limit int
		want          string
	}{
		{"past the end", 3, 1, "last valid sql_offset is 2"},
		{"far past the end", 99, 0, "it has 3 statement(s)"},
		{"negative offset", -1, 0, "cannot be negative"},
		{"negative limit", 0, -5, "cannot be negative"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := deliverScript(cascadeCLI, text, ends, false, tc.offset, tc.limit); err == nil ||
				!strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want one naming %q", err, tc.want)
			}
		})
	}

	// A script with no statements at all ("no events matched") is not a
	// paginable thing, and saying so beats an empty chunk.
	if _, err := deliverScript(cascadeCLI, "-- No events matched the specified criteria.\n", nil, false, 0, 10); err == nil {
		t.Error("paging a statement-less script was accepted")
	}
}

// The fingerprint identifies a BUILD, so it must ignore the generated-at line
// (two builds a second apart are the same script) and change on anything else
// — a caveat appearing between two chunk fetches means the coverage moved, and
// concatenating across that is the silent corruption the id exists to catch.
func TestScriptFingerprint_ignoresTheClockAndNothingElse(t *testing.T) {
	a := "-- Generated by bintrail recover at 2026-09-02 10:00:00 UTC\nBEGIN;\nDELETE FROM `t` WHERE `id` = 1;\nCOMMIT;\n"
	b := "-- Generated by bintrail recover at 2026-09-02 10:00:01 UTC\nBEGIN;\nDELETE FROM `t` WHERE `id` = 1;\nCOMMIT;\n"
	if scriptFingerprint(a) != scriptFingerprint(b) {
		t.Fatal("two builds one second apart got different ids; every chunk would then look like a different build")
	}
	caveated := strings.Replace(a, "BEGIN;", "--   - the parent may be archived\nBEGIN;", 1)
	if scriptFingerprint(a) == scriptFingerprint(caveated) {
		t.Fatal("a new caveat did not change the id; a client would concatenate across a coverage change")
	}
	if scriptFingerprint(a) == scriptFingerprint(strings.Replace(a, "`id` = 1", "`id` = 2", 1)) {
		t.Fatal("a changed statement did not change the id")
	}
}

// "chunk i of n" is offered only where it is true. A client that changes
// sql_limit between calls has no uniform paging, and a computed ordinal there
// would be a number nobody can act on.
func TestChunkNote_ordinalOnlyWhenPagingIsUniform(t *testing.T) {
	uniform := chunkNote(200, 400, 743, 200, 200, "abc123def456")
	if !strings.Contains(uniform, "chunk 2 of 4") {
		t.Errorf("uniform paging lost its ordinal: %q", uniform)
	}
	if !strings.Contains(uniform, "statements 201-400 of 743") || !strings.Contains(uniform, "sql_offset: 400") {
		t.Errorf("the note must name the range and the next offset: %q", uniform)
	}
	// Anchored on the ordinal's own tail, not on the word "chunk": the
	// guidance sentence says "concatenate the chunks in order", so a bare
	// substring check here fails on prose that is not an ordinal at all.
	ragged := chunkNote(50, 250, 743, 200, 200, "abc123def456")
	if strings.Contains(ragged, "at this sql_limit") {
		t.Errorf("a ragged offset got an ordinal it cannot support: %q", ragged)
	}
	last := chunkNote(600, 743, 743, 200, 143, "abc123def456")
	if !strings.Contains(last, "last chunk") || strings.Contains(last, "Fetch the next") {
		t.Errorf("the final chunk must say it is final: %q", last)
	}
}

// The withhold note sends a client to the CLI command that writes THIS tool's
// script, never the other one: deliverScript serves both tools and the cascade
// command has a wider blast radius than plain recover.
func TestDeliverScript_withholdNoteNamesTheCallersCLI(t *testing.T) {
	text, ends := buildFixture(3)
	big := text + strings.Repeat("-- pad\n", InlineScriptBytes/7+1)
	for _, cli := range []string{"bintrail recover", cascadeCLI} {
		d, err := deliverScript(cli, big, ends, false, 0, 0)
		if err != nil {
			t.Fatal(err)
		}
		if d.Served {
			t.Fatalf("%s: an over-cap script was served inline", cli)
		}
		if !strings.Contains(d.Note, "`"+cli+"`") {
			t.Errorf("%s: the withhold note does not name it: %s", cli, d.Note)
		}
		other := cascadeCLI
		if cli == cascadeCLI {
			other = "bintrail recover`"
		}
		if strings.Contains(d.Note, other) {
			t.Errorf("%s: the withhold note names the other tool's command: %s", cli, d.Note)
		}
	}
}

// The last chunk returns fewer statements than asked because the script
// ENDED, not because the size cap cut it; saying "reduced" there sends a
// client looking for bytes that never existed.
func TestDeliverScript_lastChunkIsNotCalledReduced(t *testing.T) {
	text, ends := buildFixture(5)
	d, err := deliverScript(cascadeCLI, text, ends, false, 3, 10)
	if err != nil {
		t.Fatal(err)
	}
	if d.From != 4 || d.To != 5 || d.More {
		t.Fatalf("unexpected chunk: %+v", d)
	}
	if strings.Contains(d.Note, "reduced") {
		t.Errorf("the last chunk claims the size cap reduced it: %s", d.Note)
	}
	if !strings.Contains(d.Note, "last chunk") {
		t.Errorf("the last chunk does not say so: %s", d.Note)
	}
}

// A single statement over the cap still comes back (it is the only way to ever
// see it), and the note says the response is oversized and why.
func TestDeliverScript_oversizedStatementNoteSaysSo(t *testing.T) {
	var b strings.Builder
	b.WriteString("BEGIN;\n")
	b.WriteString("INSERT INTO `t` VALUES ('" + strings.Repeat("x", InlineScriptBytes+10) + "');\n")
	e1 := b.Len()
	b.WriteString("DELETE FROM `t` WHERE `id` = 1;\n")
	e2 := b.Len()
	b.WriteString("COMMIT;\n")
	d, err := deliverScript(cascadeCLI, b.String(), []int{e1, e2}, false, 0, 1)
	if err != nil {
		t.Fatal(err)
	}
	if !d.Served || d.From != 1 || d.To != 1 {
		t.Fatalf("the oversized statement did not come back alone: %+v", d)
	}
	if !strings.Contains(d.Note, "over the usual") || !strings.Contains(d.Note, "cannot be split further") {
		t.Errorf("the note does not explain the oversized response: %s", d.Note)
	}
}

// Offsets that do not sit on a statement boundary are refused, never cut on.
// This is the runtime half of the guard; the emitter tests in
// internal/recovery and internal/cascaderecover are the other half.
func TestDeliverScript_refusesMisalignedOffsets(t *testing.T) {
	text, ends := buildFixture(3)
	cases := map[string][]int{
		"one byte short":      {ends[0] - 1, ends[1], ends[2]},
		"inside the preamble": {5, ends[1], ends[2]},
		"not increasing":      {ends[1], ends[0], ends[2]},
		"duplicate":           {ends[0], ends[0], ends[2]},
		"past the end":        {ends[0], ends[1], len(text) + 3},
	}
	for name, bad := range cases {
		if _, err := deliverScript(cascadeCLI, text, bad, false, 0, 1); err == nil {
			t.Errorf("%s: misaligned offsets were accepted", name)
		} else if strings.Contains(err.Error(), "--") {
			t.Errorf("%s: the refusal names a CLI flag: %v", name, err)
		}
	}
	if _, err := deliverScript(cascadeCLI, text, ends, false, 0, 1); err != nil {
		t.Fatalf("well-formed offsets refused: %v", err)
	}
	// A whole return does not depend on the offsets and is served regardless:
	// a bad list must not take the non-chunked path down with it.
	if d, err := deliverScript(cascadeCLI, text, cases["inside the preamble"], false, 0, 0); err != nil || !d.Served {
		t.Errorf("a whole return was refused over offsets it does not use: %v", err)
	}
}

// A page the size cap cut short says "reduced" even when the ask overshoots
// the end of the script: "give me everything" answered with half and no word
// about it is the silent reduction the schema text promises never happens.
func TestDeliverScript_reducedIsSaidWhenTheAskOvershootsTheEnd(t *testing.T) {
	big, ends := buildFixture(4000)
	d, err := deliverScript(cascadeCLI, big, ends, false, 0, 5000)
	if err != nil {
		t.Fatal(err)
	}
	if !d.More || !strings.Contains(d.Note, "reduced") {
		t.Errorf("the cap cut the page but the note does not say reduced: more=%v note=%s", d.More, d.Note)
	}
}

// Paging from a late offset fits statements by the bytes remaining FROM that
// offset, not from the start of the script; and an ordinary under-cap chunk
// never gets the oversized-statement note.
func TestDeliverScript_pagesFromALateOffsetByRemainingBytes(t *testing.T) {
	big, ends := buildFixture(4000)
	d, err := deliverScript(cascadeCLI, big, ends, false, 3000, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.More || d.To != 4000 || d.From != 3001 {
		t.Fatalf("late offset did not page by the bytes remaining from it: %+v", d)
	}
	if strings.Contains(d.Note, "cannot be split further") {
		t.Errorf("a late, under-cap chunk got the oversized-statement note: %s", d.Note)
	}
	if d.NextOffset != 0 {
		t.Errorf("the last chunk offers a next offset: %d", d.NextOffset)
	}
}

// "chunk i of n" is computed on the ASKED limit and only while the walk is
// uniform: dividing by what was given said "chunk 6 of 6" on the third and
// last of three pages.
func TestChunkNote_ordinalCountsTheAskedLimit(t *testing.T) {
	// 12 statements, sql_limit 5: pages 1-5, 6-10, 11-12. The last page is
	// short, and 10 % 2 == 0 would have made it "chunk 6 of 6".
	last := chunkNote(10, 12, 12, 5, 2, "abc123def456")
	if !strings.Contains(last, "chunk 3 of 3") {
		t.Errorf("the short last page lost or miscounted its ordinal: %q", last)
	}
	if strings.Contains(last, "reduced") {
		t.Errorf("the short last page claims a size reduction: %q", last)
	}
	// A page the cap cut short mid-walk offers no ordinal: later offsets are
	// no longer multiples of the asked limit.
	cut := chunkNote(0, 3, 12, 5, 3, "abc123def456")
	if strings.Contains(cut, "at this sql_limit") {
		t.Errorf("a cap-reduced page got an ordinal it cannot support: %q", cut)
	}
	if !strings.Contains(cut, "reduced to 3") {
		t.Errorf("a cap-reduced page does not say so: %q", cut)
	}
	// A ragged final page (offset 9 is no multiple of the asked 5, gave 3)
	// has no ordinal either, even though 9 happens to divide by what was
	// given.
	ragged := chunkNote(9, 12, 12, 5, 3, "abc123def456")
	if strings.Contains(ragged, "at this sql_limit") {
		t.Errorf("a ragged last page got an ordinal computed on what it gave: %q", ragged)
	}
}

// The cap is measured on what crosses the wire: the chunk rides a JSON
// string, and escaping grows it (every backslash doubles). A script whose raw
// bytes fit but whose escaped bytes do not is withheld, and asked for by
// chunk it comes back alone with the oversized note.
func TestDeliverScript_sizesTheChunkOnTheWire(t *testing.T) {
	var b strings.Builder
	b.WriteString("BEGIN;\n")
	b.WriteString("INSERT INTO `t` VALUES ('" + strings.Repeat(`\`, InlineScriptBytes*3/5) + "');\n")
	e1 := b.Len()
	b.WriteString("DELETE FROM `t` WHERE `id` = 1;\n")
	e2 := b.Len()
	b.WriteString("COMMIT;\n")
	text := b.String()
	if len(text) > InlineScriptBytes || wireLen(text) <= InlineScriptBytes {
		t.Fatalf("fixture must fit raw (%d) and not on the wire (%d)", len(text), wireLen(text))
	}
	d, err := deliverScript(cascadeCLI, text, []int{e1, e2}, false, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.Served {
		t.Fatalf("a script over the cap on the wire was served inline (%d raw, %d wire)", len(text), wireLen(text))
	}
	d, err = deliverScript(cascadeCLI, text, []int{e1, e2}, false, 0, 2)
	if err != nil {
		t.Fatal(err)
	}
	if d.To != 1 || !d.More {
		t.Fatalf("the escaped-oversized statement was not paged alone: %+v", d)
	}
	if !strings.Contains(d.Note, "on the wire") {
		t.Errorf("the oversized note does not explain the wire size: %s", d.Note)
	}
}

// The trailer rides the last page and counts toward its size, so two
// statements that end just under the cap do not overflow it with COMMIT and
// the appended notes; and the note never blames a single statement for what
// the trailer did.
func TestDeliverScript_lastPageCountsTheTrailer(t *testing.T) {
	var b strings.Builder
	b.WriteString("BEGIN;\n")
	stmt := "INSERT INTO `t` VALUES ('" + strings.Repeat("x", InlineScriptBytes/2-40) + "');\n"
	b.WriteString(stmt)
	e1 := b.Len()
	b.WriteString(stmt)
	e2 := b.Len()
	b.WriteString("\nCOMMIT;\n-- 2 reversal statement(s) generated.\n")
	text := b.String()
	if e2 > InlineScriptBytes || len(text) <= InlineScriptBytes {
		t.Fatalf("fixture must fit without the trailer (%d) and not with it (%d)", e2, len(text))
	}
	d, err := deliverScript(cascadeCLI, text, []int{e1, e2}, false, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if d.Served {
		t.Fatal("served inline although the trailer pushes it over the cap")
	}
	d, err = deliverScript(cascadeCLI, text, []int{e1, e2}, false, 0, 2)
	if err != nil {
		t.Fatal(err)
	}
	if d.To != 1 || !d.More || strings.Contains(d.Note, "cannot be split further") {
		t.Fatalf("the trailer was not counted on the last page, or a statement was blamed for it: %+v", d)
	}
}

// An explicit page over a script with no statements is refused whichever of
// the two parameters made it explicit.
func TestDeliverScript_offsetAloneOnNoStatementsIsRefused(t *testing.T) {
	const noEvents = "-- No events matched the specified criteria.\n"
	if _, err := deliverScript(cascadeCLI, noEvents, nil, false, 1, 0); err == nil {
		t.Error("sql_offset alone on a statement-less script was not refused")
	}
}

// A shrunken script (the build moved) lands on the past-the-end refusal; it
// carries the script id, the client's first chance to see why.
func TestDeliverScript_pastTheEndNamesTheScriptID(t *testing.T) {
	text, ends := buildFixture(3)
	_, err := deliverScript(cascadeCLI, text, ends, false, 7, 1)
	if err == nil || !strings.Contains(err.Error(), scriptFingerprint(text)) {
		t.Errorf("the past-the-end refusal does not carry the script id: %v", err)
	}
}

// The fingerprint skips exactly one stamp line, by position: a captured value
// that starts a line with the same prefix is content and must change the id.
// The two scripts here differ ONLY inside that mimicking line, so a
// fingerprint that skipped every matching line would call them the same.
func TestScriptFingerprint_skipsOnlyTheFirstStampLine(t *testing.T) {
	text, _ := buildFixture(2)
	mimic := func(when string) string {
		return strings.Replace(text, "DELETE FROM `t` WHERE `id` = 1;\n",
			"UPDATE `t` SET `note` = 'x\n-- Generated by bintrail recover at "+when+"' WHERE `id` = 1;\n", 1)
	}
	a, b := mimic("1999-01-01 00:00:00 UTC"), mimic("2000-01-01 00:00:00 UTC")
	if a == b || a == text {
		t.Fatal("fixture unchanged")
	}
	if scriptFingerprint(a) == scriptFingerprint(b) {
		t.Error("a value line that mimics the stamp was excluded from the fingerprint")
	}
	// And the real stamp line is still excluded: the same content a second
	// apart shares an id.
	c := strings.Replace(a, "2026-09-02 10:00:00 UTC", "2026-09-02 10:00:01 UTC", 1)
	if scriptFingerprint(a) != scriptFingerprint(c) {
		t.Error("the generator's own stamp line changed the fingerprint")
	}
}
