package parser

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

// TestParseDDL_shapesItUsedToMiss is #1664: a schema change written with a
// leading comment, a modifier between the keywords, or a line break between
// them is still DDL, so it gets its schema snapshot and its schema_changes row.
func TestParseDDL_shapesItUsedToMiss(t *testing.T) {
	var buf bytes.Buffer
	logger := newTestLogger(&buf)
	ts := time.Date(2026, 9, 15, 12, 0, 0, 0, time.UTC)

	for _, tc := range []struct {
		name, query   string
		ddlType       DDLKind
		schema, table string
	}{
		{"leading block comment", "/* app */ ALTER TABLE t MODIFY c BIGINT", DDLAlterTable, "", "t"},
		{"leading line comment", "-- migration 42\nALTER TABLE t ADD COLUMN c INT", DDLAlterTable, "", "t"},
		{"leading hash comment", "# cleanup\nDROP TABLE t", DDLDropTable, "", "t"},
		{"two leading comments", "/* a */ -- b\n/* c */ CREATE TABLE t (id INT)", DDLCreateTable, "", "t"},
		{"ALTER ONLINE", "ALTER ONLINE TABLE t ADD COLUMN c INT", DDLAlterTable, "", "t"},
		{"ALTER IGNORE", "ALTER IGNORE TABLE t ADD UNIQUE KEY (c)", DDLAlterTable, "", "t"},
		{"ALTER ONLINE IGNORE with a schema", "alter online ignore table db.t add column c int", DDLAlterTable, "db", "t"},
		{"line break between the keywords", "ALTER\n  TABLE `db`.`t` ADD COLUMN c INT", DDLAlterTable, "db", "t"},
		{"CRLF and a tab between the keywords", "DROP\r\n\tTABLE t", DDLDropTable, "", "t"},
		{"comment between the keywords (gh-ost cut-over)", "rename /* gh-ost */ table `db`.`t` to `db`.`_t_del`, `db`.`_t_gho` to `db`.`t`", DDLRenameTable, "db", "t"},
		{"comment between TRUNCATE and TABLE", "TRUNCATE /* nightly */ TABLE t", DDLTruncateTable, "", "t"},
		{"MariaDB ALTER TABLE IF EXISTS", "ALTER TABLE IF EXISTS t ADD COLUMN c INT", DDLAlterTable, "", "t"},
		{"MariaDB CREATE OR REPLACE", "CREATE OR REPLACE TABLE t (id INT)", DDLCreateTable, "", "t"},
		{"MariaDB RENAME TABLE IF EXISTS", "RENAME TABLE IF EXISTS a TO b", DDLRenameTable, "", "a"},
		{"MariaDB trailing server comment", "DROP TABLE `t` /* generated by server */", DDLDropTable, "", "t"},
		{"schema quoted, table not", "ALTER TABLE `db`.t ADD COLUMN c INT", DDLAlterTable, "db", "t"},
		{"schema not quoted, table quoted", "ALTER TABLE db.`t` ADD COLUMN c INT", DDLAlterTable, "db", "t"},
		{"dollar sign in a name", "ALTER TABLE db.t$1 ADD COLUMN c INT", DDLAlterTable, "db", "t$1"},
		{"a comment where the name starts", "ALTER TABLE /* x */ t ADD COLUMN c INT", DDLAlterTable, "", "t"},
		{"a comment with no space around it", "ALTER/**/TABLE t ADD COLUMN c INT", DDLAlterTable, "", "t"},
		{"mysqldump executable comment around IF NOT EXISTS", "CREATE TABLE /*!32312 IF NOT EXISTS*/ `t` (id INT)", DDLCreateTable, "", "t"},
		{"backticked name holding comment markers", "ALTER TABLE `a/*b` ADD COLUMN c INT", DDLAlterTable, "", "a/*b"},
		// Shapes the old prefix check caught, which must stay caught.
		{"unquoted name with a non-ASCII letter", "ALTER TABLE ñandú ADD COLUMN c INT", DDLAlterTable, "", "ñandú"},
		{"unquoted name with an accent inside", "ALTER TABLE shop.categoría ADD COLUMN c INT", DDLAlterTable, "shop", "categoría"},
		{"ANSI_QUOTES double-quoted names", `ALTER TABLE "shop"."orders" ADD COLUMN c INT`, DDLAlterTable, "shop", "orders"},
		{"no space before a backtick", "DROP TABLE`t`", DDLDropTable, "", "t"},
		{"DROP TABLES", "DROP TABLES t", DDLDropTable, "", "t"},
		{"RENAME TABLES", "RENAME TABLES a TO b", DDLRenameTable, "", "a"},
		{"TRUNCATE a table whose name starts with table", "TRUNCATE tables_log", DDLTruncateTable, "", "tables_log"},
		{"the verb with a name it cannot read is still DDL", "DROP TABLE", DDLDropTable, "", ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ev, ok := parseDDL(logger, "binlog.000001", 100, ts, "", tc.query, "", 0)
			if !ok {
				t.Fatalf("parseDDL(%q) returned false, want %s", tc.query, tc.ddlType)
			}
			if ev.DDLType != tc.ddlType || ev.Schema != tc.schema || ev.Table != tc.table {
				t.Errorf("parseDDL(%q) = %s %q.%q, want %s %q.%q", tc.query, ev.DDLType, ev.Schema, ev.Table, tc.ddlType, tc.schema, tc.table)
			}
			if ev.DDLQuery != tc.query {
				t.Errorf("DDLQuery = %q, want the statement as logged", ev.DDLQuery)
			}
		})
	}
}

// TestParseDDL_notTableDDL: what must stay out, because a DDL event takes a
// schema snapshot and a TRUNCATE, DROP or RENAME refuses every reconstruct over
// its window. A temporary table is not in any snapshot; MySQL logs the drop of
// one, at session end, with TEMPORARY inside a version comment.
func TestParseDDL_notTableDDL(t *testing.T) {
	var buf bytes.Buffer
	logger := newTestLogger(&buf)
	ts := time.Date(2026, 9, 15, 12, 0, 0, 0, time.UTC)

	for _, query := range []string{
		"DROP /*!40005 TEMPORARY */ TABLE IF EXISTS `t`",
		// mysqldump wraps every table's rows in these; they change no definition.
		"/*!40000 ALTER TABLE `t` DISABLE KEYS */",
		"ALTER TABLE t ENABLE KEYS;",
		"DROP TEMPORARY TABLE IF EXISTS t",
		"CREATE TEMPORARY TABLE t (id INT)",
		"CREATE /*M!100000 TEMPORARY */ TABLE t (id INT)",
		"ALTER TABLESPACE ts ADD DATAFILE 'ts2.ibd'",
		"CREATE TABLESPACE ts ADD DATAFILE 'ts.ibd'",
		"DROP TABLESPACE ts",
		"ALTER VIEW v AS SELECT 1",
		"DROP VIEW v",
		"/* ALTER TABLE t ADD COLUMN c INT */ SELECT 1",
		"SELECT 'ALTER TABLE t'",
		"INSERT INTO log VALUES ('DROP TABLE x')",
		"/* ALTER TABLE t",
		"-- DROP TABLE t",
		"",
	} {
		if ev, ok := parseDDL(logger, "binlog.000001", 100, ts, "", query, "", 0); ok {
			t.Errorf("parseDDL(%q) = %s %q.%q, want not DDL", query, ev.DDLType, ev.Schema, ev.Table)
		}
	}
}

// TestNormalizeDDL_boundedOnHugeStatements: parseDDL runs on every QUERY_EVENT,
// including statement-format DML many megabytes long, and only the head of a
// statement can name a DDL verb and its table.
func TestNormalizeDDL_boundedOnHugeStatements(t *testing.T) {
	huge := "INSERT INTO t VALUES ('" + strings.Repeat("x", 8<<20) + "')"
	if got := normalizeDDL(huge); len(got) > 2*ddlHeadLimit {
		t.Fatalf("normalized %d bytes of an 8 MiB statement, want at most %d", len(got), 2*ddlHeadLimit)
	}
	long := "ALTER TABLE `" + strings.Repeat("n", 64) + "`.`" + strings.Repeat("m", 64) + "` ADD COLUMN c INT"
	var buf bytes.Buffer
	ev, ok := parseDDL(newTestLogger(&buf), "binlog.000001", 100, time.Now(), "", long, "", 0)
	if !ok || ev.Table != strings.Repeat("m", 64) {
		t.Fatalf("a statement with the longest names MySQL allows: ok=%v table=%q", ok, ev.Table)
	}
}
