//go:build integration

package parser_test

import (
	"context"
	"errors"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/dbtrail/dbtrail/internal/config"
	"github.com/dbtrail/dbtrail/internal/indexer"
	"github.com/dbtrail/dbtrail/internal/parser"
	"github.com/dbtrail/dbtrail/internal/reconstruct"
	"github.com/dbtrail/dbtrail/internal/testutil"
)

// TestParseFile_everyTableADropOrRenameNames runs a DROP of two tables and a
// RENAME on a real server, reads the binlog MySQL wrote (which rewrites the
// DROP as "DROP TABLE `a`,`b` /* generated by server */"), records the events
// the way capture does, and asks the destructive-DDL guard about the tables
// that are NOT named first: the second table dropped and the rename's new
// name. Before, only the first name of each statement was recorded, so the
// guard let a reconstruct of those tables through.
func TestParseFile_everyTableADropOrRenameNames(t *testing.T) {
	testutil.SkipIfNoMySQL(t)

	sourceDB, sourceName := testutil.CreateTestDB(t)
	for _, tbl := range []string{"ddl_tmp", "ddl_gone", "ddl_new"} {
		testutil.MustExec(t, sourceDB, "CREATE TABLE "+tbl+" (id INT PRIMARY KEY)")
	}
	testutil.MustExec(t, sourceDB, "FLUSH BINARY LOGS")
	currentBinlog, _, err := config.CurrentBinlogPosition(sourceDB)
	if err != nil {
		t.Fatalf("CurrentBinlogPosition: %v", err)
	}
	before := time.Now().UTC().Add(-time.Minute)
	testutil.MustExec(t, sourceDB, "DROP TABLE ddl_tmp, ddl_gone")
	testutil.MustExec(t, sourceDB, "RENAME TABLE ddl_new TO ddl_orders")
	testutil.MustExec(t, sourceDB, "FLUSH BINARY LOGS")
	after := time.Now().UTC().Add(time.Minute)

	tmpDir := t.TempDir()
	cpCmd := exec.Command("docker", "cp",
		fmt.Sprintf("bintrail-test-mysql:/var/lib/mysql/%s", currentBinlog),
		filepath.Join(tmpDir, currentBinlog))
	if out, err := cpCmd.CombinedOutput(); err != nil {
		t.Fatalf("docker cp %s failed: %v\n%s", currentBinlog, err, out)
	}
	p := parser.New(tmpDir, nil, parser.Filters{Schemas: map[string]bool{sourceName: true}}, nil)
	events := make(chan parser.Event, 100)
	errCh := make(chan error, 1)
	go func() {
		defer close(events)
		errCh <- p.ParseFile(context.Background(), currentBinlog, events)
	}()
	all := drainEvents(events)
	if err := <-errCh; err != nil {
		t.Fatalf("ParseFile: %v", err)
	}

	indexDB, _ := testutil.CreateTestDB(t)
	testutil.InitIndexTables(t, indexDB)
	var drop, rename []string
	for _, ev := range all {
		if ev.EventType != parser.EventDDL || ev.Schema != sourceName {
			continue
		}
		var names []string
		for _, n := range ev.DDLTables {
			names = append(names, n.Table)
		}
		switch ev.DDLType {
		case parser.DDLDropTable:
			drop = names
		case parser.DDLRenameTable:
			rename = names
		default:
			continue
		}
		if err := indexer.InsertSchemaChange(indexDB, ev, nil); err != nil {
			t.Fatalf("InsertSchemaChange(%q): %v", ev.DDLQuery, err)
		}
	}
	if strings.Join(drop, ",") != "ddl_tmp,ddl_gone" || strings.Join(rename, ",") != "ddl_new,ddl_orders" {
		t.Fatalf("names read from the binlog: drop %q, rename %q; want both tables of the DROP and both sides of the RENAME", drop, rename)
	}
	for _, tbl := range []string{"ddl_gone", "ddl_orders"} {
		err := reconstruct.CheckDestructiveDDL(context.Background(), indexDB, sourceName, tbl, before, after)
		if !errors.Is(err, reconstruct.ErrDestructiveDDL) {
			t.Errorf("%s: CheckDestructiveDDL = %v, want a refusal: a statement dropped or renamed it without naming it first", tbl, err)
		}
	}
}
