package parser

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

// TestParseDDL_everyTableItNames: a DROP or RENAME can name several tables,
// and each one's rows stop being what they were. Every name reaches the event,
// in order, so each gets its schema_changes row and the destructive-DDL guards
// (reconstruct, verify) see it; before, only the first name was recorded.
func TestParseDDL_everyTableItNames(t *testing.T) {
	var buf bytes.Buffer
	logger := newTestLogger(&buf)
	ts := time.Date(2026, 9, 21, 12, 0, 0, 0, time.UTC)

	var long strings.Builder
	var longWant []string
	long.WriteString("DROP TABLE ")
	for i := range 60 {
		if i > 0 {
			long.WriteString(", ")
		}
		name := "a_table_with_a_long_name_" + string(rune('a'+i%26)) + strings.Repeat("x", i%7)
		long.WriteString("`" + name + "`")
		longWant = append(longWant, "db1."+name)
	}
	if long.Len() <= ddlHeadLimit {
		t.Fatalf("fixture: the long DROP is %d bytes, want more than the %d-byte head", long.Len(), ddlHeadLimit)
	}

	for _, tc := range []struct {
		name, query, defaultSchema string
		ddlType                    DDLKind
		want                       []string // "schema.table", in order; nil = no list
	}{
		{"one table", "DROP TABLE a", "db1", DDLDropTable, []string{"db1.a"}},
		{"two tables", "DROP TABLE a, b", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"IF EXISTS", "DROP TABLE IF EXISTS a, b", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"TABLES and no space after the comma", "DROP TABLES a,b", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"one name qualified, one not", "DROP TABLE a, db2.b", "db1", DDLDropTable, []string{"db1.a", "db2.b"}},
		{"no default database", "DROP TABLE a, db2.b", "", DDLDropTable, []string{".a", "db2.b"}},
		{"a comma inside a quoted name", "DROP TABLE `a,b`, c", "db1", DDLDropTable, []string{"db1.a,b", "db1.c"}},
		{"ANSI_QUOTES", `DROP TABLE "s"."a", "b"`, "db1", DDLDropTable, []string{"s.a", "db1.b"}},
		{"spaces around dots and commas", "DROP TABLE db . a , db . b", "", DDLDropTable, []string{"db.a", "db.b"}},
		{"CASCADE is not a table", "DROP TABLE a, b CASCADE", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"RESTRICT is not a table", "DROP TABLE a RESTRICT", "db1", DDLDropTable, []string{"db1.a"}},
		{"MariaDB WAIT", "DROP TABLE a, b WAIT 5", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"MariaDB NOWAIT", "DROP TABLE a NOWAIT", "db1", DDLDropTable, []string{"db1.a"}},
		{"trailing semicolon", "DROP TABLE a, b;", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"comments between the names", "DROP TABLE a /* x */, -- y\n b", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"the server's own comment", "DROP TABLE `a`,`b` /* generated by server */", "db1", DDLDropTable, []string{"db1.a", "db1.b"}},
		{"a list longer than the head", long.String(), "db1", DDLDropTable, longWant},
		{"doubled backtick inside a name", "DROP TABLE `a``b`, c", "db1", DDLDropTable, []string{"db1.a`b", "db1.c"}},
		{"doubled quote inside an ANSI name", `DROP TABLE "a""b"`, "db1", DDLDropTable, []string{`db1.a"b`}},
		{"non-ASCII names", "DROP TABLE ñandú, shop.categoría", "db1", DDLDropTable, []string{"db1.ñandú", "shop.categoría"}},
		{"garbage after the first name keeps it", "DROP TABLE a, (b)", "db1", DDLDropTable, []string{"db1.a"}},
		{"no name at all", "DROP TABLE", "db1", DDLDropTable, nil},

		{"rename one", "RENAME TABLE a TO b", "db1", DDLRenameTable, []string{"db1.a", "db1.b"}},
		{"rename two pairs", "RENAME TABLE a TO b, c TO d", "db1", DDLRenameTable, []string{"db1.a", "db1.b", "db1.c", "db1.d"}},
		{"rename lowercase to, qualified", "rename table db1.a to db2.b", "", DDLRenameTable, []string{"db1.a", "db2.b"}},
		{"rename swap keeps every name in order", "RENAME TABLE a TO tmp, b TO a, tmp TO b", "db1", DDLRenameTable,
			[]string{"db1.a", "db1.tmp", "db1.b", "db1.a", "db1.tmp", "db1.b"}},
		{"gh-ost cut-over", "rename /* gh-ost */ table `db`.`t` to `db`.`_t_del`, `db`.`_t_gho` to `db`.`t`", "", DDLRenameTable,
			[]string{"db.t", "db._t_del", "db._t_gho", "db.t"}},
		{"MariaDB RENAME IF EXISTS with WAIT", "RENAME TABLE IF EXISTS a WAIT 1 TO b", "db1", DDLRenameTable, []string{"db1.a", "db1.b"}},
		{"MariaDB RENAME NOWAIT", "RENAME TABLE a NOWAIT TO b", "db1", DDLRenameTable, []string{"db1.a", "db1.b"}},
		{"rename without TO keeps the source", "RENAME TABLE a", "db1", DDLRenameTable, []string{"db1.a"}},
		{"MariaDB fractional WAIT", "RENAME TABLE a WAIT 1.5 TO b", "db1", DDLRenameTable, []string{"db1.a", "db1.b"}},
		{"rename target in the session's database", "RENAME TABLE db1.a TO b", "d", DDLRenameTable, []string{"db1.a", "d.b"}},
		{"an empty quoted name ends the list", "DROP TABLE a, ``, b", "db1", DDLDropTable, []string{"db1.a"}},

		{"ALTER has no list", "ALTER TABLE a ADD COLUMN c INT", "db1", DDLAlterTable, nil},
		{"CREATE has no list", "CREATE TABLE a (id INT)", "db1", DDLCreateTable, nil},
		{"TRUNCATE has no list", "TRUNCATE TABLE a", "db1", DDLTruncateTable, nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ev, ok := parseDDL(logger, "binlog.000001", 100, ts, "", tc.query, tc.defaultSchema, 0)
			if !ok {
				t.Fatalf("parseDDL(%q) returned false, want %s", tc.query, tc.ddlType)
			}
			if ev.DDLType != tc.ddlType {
				t.Fatalf("parseDDL(%q) type %s, want %s", tc.query, ev.DDLType, tc.ddlType)
			}
			var got []string
			for _, n := range ev.DDLTables {
				got = append(got, n.Schema+"."+n.Table)
			}
			if strings.Join(got, "|") != strings.Join(tc.want, "|") || len(got) != len(tc.want) {
				t.Fatalf("parseDDL(%q) tables\n got: %q\nwant: %q", tc.query, got, tc.want)
			}
			// The event's own table is the first name, so the two never disagree.
			if len(tc.want) > 0 && ev.Schema+"."+ev.Table != tc.want[0] {
				t.Errorf("parseDDL(%q) = %q.%q, want the first name %q", tc.query, ev.Schema, ev.Table, tc.want[0])
			}
			if ev.DDLQuery != tc.query {
				t.Errorf("DDLQuery = %q, want the statement as logged", ev.DDLQuery)
			}
		})
	}
}

// A TEMPORARY table is in no snapshot, so its drop stays out, list or not.
func TestParseDDL_temporaryListStaysOut(t *testing.T) {
	var buf bytes.Buffer
	if _, ok := parseDDL(newTestLogger(&buf), "binlog.000001", 100, time.Now(), "", "DROP /*!40005 TEMPORARY */ TABLE IF EXISTS `a`, `b`", "db1", 0); ok {
		t.Fatal("a DROP TEMPORARY TABLE list was taken for table DDL")
	}
}

// A keyword is a whole word: TO must not be read out of the front of TOWELS.
func TestDDLScanner_keywordIsAWholeWord(t *testing.T) {
	for _, tc := range []struct {
		s, kw string
		want  bool
	}{
		{" TO b", "TO", true},
		{" to b", "TO", true},
		{" TOWELS", "TO", false},
		{" TO$x", "TO", false},
		{" TOñ", "TO", false},
		{" IF EXISTS a", "IF EXISTS", true},
		{" IF EXISTSa", "IF EXISTS", false},
	} {
		sc := ddlScanner{s: tc.s}
		if got := sc.keyword(tc.kw); got != tc.want {
			t.Errorf("keyword(%q) on %q = %v, want %v", tc.kw, tc.s, got, tc.want)
		}
	}
}
