package cliapp

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/dbtrail/dbtrail/internal/cli"
)

var initShimCmd = &cobra.Command{
	Use:   "init-shim",
	Short: "Generate a shim.yaml for `bintrail shim`",
	Long: `Generates a starter shim.yaml that the in-process ` + "`bintrail shim`" + ` reads
to serve time-travel SQL: ` + "`SELECT * FROM _flashback.<table> AS OF '<ts>'" + `
` + "`WHERE <col> = <value>`" + ` and the matching _diff / _snapshot virtual schemas.

Reads BINTRAIL_SOURCE_DSN and BINTRAIL_SERVER_ID from .bintrail.env (or the
environment) to populate the tenant block. The mysql_user / mysql_password
credentials your application uses to connect through ProxySQL are emitted
as TODO comments; fill them in by hand. The shim validates both the
username and the cleartext password; bintrail proxysql-config recomputes
the SHA1 from mysql_password for ProxySQL's own user table.

Use --output - to write to stdout instead of a file.`,
	RunE: runInitShim,
}

var (
	isOut    string
	isListen string
)

func init() {
	cli.AddOutputFlag(initShimCmd, &isOut, "shim.yaml", "Output path for the generated shim config (use - for stdout)", cli.OutAlias)
	initShimCmd.Flags().StringVar(&isListen, "listen", "127.0.0.1:3308", "Listen address for `bintrail shim`'s MySQL protocol port")
	bindCommandEnv(initShimCmd)
	rootCmd.AddCommand(initShimCmd)
}

func runInitShim(cmd *cobra.Command, args []string) error {
	sourceDSN := os.Getenv("BINTRAIL_SOURCE_DSN")
	serverID := os.Getenv("BINTRAIL_SERVER_ID")

	var missing []string
	if sourceDSN == "" {
		missing = append(missing, "BINTRAIL_SOURCE_DSN")
	}
	if serverID == "" {
		missing = append(missing, "BINTRAIL_SERVER_ID")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required env var(s): %s\nRun 'bintrail config init' to scaffold .bintrail.env, then set these values.", strings.Join(missing, ", "))
	}

	// YAML single-quoted scalars cannot contain literal newlines; reject
	// rather than silently emit a malformed file.
	for _, v := range []struct{ name, val string }{
		{"BINTRAIL_SOURCE_DSN", sourceDSN},
		{"BINTRAIL_SERVER_ID", serverID},
	} {
		if strings.ContainsAny(v.val, "\r\n") {
			return fmt.Errorf("%s contains a newline character; remove it before generating shim.yaml", v.name)
		}
	}

	content := generateShimYAML(sourceDSN, serverID, isListen)

	if isOut == "-" {
		_, err := io.WriteString(os.Stdout, content)
		return err
	}

	if _, err := os.Stat(isOut); err == nil {
		return fmt.Errorf("file already exists: %s\nRemove it first or edit it directly.", isOut)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("cannot check %s: %w", isOut, err)
	}

	if err := os.WriteFile(isOut, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", isOut, err)
	}

	fmt.Printf("Shim configuration written to %s\n", isOut)
	fmt.Println("Edit the file to fill in mysql_user and mysql_password, then run 'bintrail shim'.")
	return nil
}

func generateShimYAML(sourceDSN, serverID, listen string) string {
	var sb strings.Builder
	sb.WriteString("# Bintrail time-travel SQL: shim configuration\n")
	sb.WriteString("# Generated by bintrail init-shim. See docs/time-travel-sql.md.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Fill in mysql_user and mysql_password below; these are the\n")
	sb.WriteString("# credentials your application uses to connect through ProxySQL.\n")
	sb.WriteString("# `bintrail shim` validates both the username and the cleartext\n")
	sb.WriteString("# password; `bintrail proxysql-config` recomputes the SHA1 from\n")
	sb.WriteString("# mysql_password for ProxySQL's own user table.\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "listen: %s\n", yamlQuote(listen))
	sb.WriteString("\n")
	sb.WriteString("tenants:\n")
	fmt.Fprintf(&sb, "  - server_id: %s\n", yamlQuote(serverID))
	fmt.Fprintf(&sb, "    source_dsn: %s\n", yamlQuote(sourceDSN))
	sb.WriteString("    # TODO: fill in your application's MySQL credentials\n")
	sb.WriteString("    # mysql_user: app_user\n")
	sb.WriteString("    # mysql_password: '<cleartext>'\n")
	return sb.String()
}

// yamlQuote wraps s as a YAML single-quoted scalar, doubling any embedded
// single quotes per the YAML 1.2 spec. Single-quoted scalars treat all
// other characters literally — no escape processing — so this safely
// handles values containing ':', '#', '{', '[', leading whitespace, and
// other YAML-syntactic characters that would otherwise need quoting.
func yamlQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
