package cascaderecover_test

import (
	"bytes"
	"slices"
	"strings"
	"testing"

	"github.com/dbtrail/dbtrail/internal/cascade"
	"github.com/dbtrail/dbtrail/internal/cascaderecover"
	"github.com/dbtrail/dbtrail/internal/event"
	"github.com/dbtrail/dbtrail/internal/query"
	"github.com/dbtrail/dbtrail/internal/recovery"
)

// TestEmitSQLIndexed_endsCloseStatements guards the offsets the chunked MCP
// delivery cuts on (#1438), driven by the REAL emitter over all three append
// sites: the generator's reversals (rebased past the cascade preamble), the
// SET NULL restorations and the ON UPDATE key restorations. Every end must sit
// just past a `;` and its newline, strictly increasing; a rebase that forgets
// the preamble lands every cut in the header comments while the chunks still
// concatenate into the script.
func TestEmitSQLIndexed_endsCloseStatements(t *testing.T) {
	hdr := cascaderecover.Header{Schema: "shop", Table: "orders", Parents: 1, Children: 1}
	rows := []query.ResultRow{
		{EventType: event.EventDelete, SchemaName: "shop", TableName: "orders", PKValues: "1",
			RowBefore: map[string]any{"id": float64(1), "note": "a;\nb"}},
		{EventType: event.EventDelete, SchemaName: "shop", TableName: "orders", PKValues: "2",
			RowBefore: map[string]any{"id": float64(2)}},
	}
	setNull := []cascade.SetNullRestore{{
		Schema: "shop", Table: "orders", Column: "customer_id", Value: 42, PKValues: "7",
		Row: map[string]any{"id": 7, "customer_id": nil},
	}}
	keyUpdates := []cascade.FKKeyRestore{{
		Schema: "shop", Table: "orders", Column: "customer_id", OldValue: 5, NewValue: 6, PKValues: "8",
		Row: map[string]any{"id": 8, "customer_id": 6},
	}}
	r := orderResolver()
	var buf bytes.Buffer
	n, ends, err := cascaderecover.EmitSQLIndexed(&buf, recovery.New(nil, r), slices.Clone(rows), setNull, keyUpdates, r, hdr) // the generator reverses its input in place
	if err != nil {
		t.Fatal(err)
	}
	text := buf.String()
	if n != 4 || len(ends) != 4 {
		t.Fatalf("n=%d ends=%d, want 4 statements over the three append sites", n, len(ends))
	}
	prev := 0
	for i, e := range ends {
		if e <= prev || e > len(text) || e < 2 || text[e-1] != '\n' || text[e-2] != ';' {
			lo, hi := max(0, e-20), min(len(text), e+5)
			t.Fatalf("end %d (byte %d) does not close a statement; text around it: %q", i+1, e, text[lo:hi])
		}
		prev = e
	}
	// The generator's ends were rebased past the cascade preamble.
	if fk := strings.Index(text, "SET FOREIGN_KEY_CHECKS=0;\n"); fk < 0 || ends[0] <= fk {
		t.Fatalf("first end (%d) sits inside the cascade preamble (FK-disable at %d)", ends[0], fk)
	}
	// Each segment holds exactly one statement of the expected kind, in order.
	kinds := []string{"INSERT INTO", "INSERT INTO", "IS NULL", "ON UPDATE cascade"}
	prev = 0
	for i, e := range ends {
		seg := text[prev:e]
		if !strings.Contains(seg, kinds[i]) {
			t.Errorf("segment %d lacks %q: %q", i+1, kinds[i], seg)
		}
		prev = e
	}
	// Byte-identical to the unindexed emission.
	var plain bytes.Buffer
	if _, err := cascaderecover.EmitSQL(&plain, recovery.New(nil, r), slices.Clone(rows), setNull, keyUpdates, r, hdr); err != nil {
		t.Fatal(err)
	}
	if a, b := stripGeneratedAt(plain.String()), stripGeneratedAt(text); a != b {
		t.Errorf("EmitSQLIndexed and EmitSQL render different scripts.\n--- plain ---\n%s\n--- indexed ---\n%s", a, b)
	}
}

// stripGeneratedAt drops the generator's timestamp line, the one byte-level
// difference between two builds of the same script.
func stripGeneratedAt(s string) string {
	var out []string
	for line := range strings.SplitSeq(s, "\n") {
		if strings.HasPrefix(line, "-- Generated by bintrail recover at ") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}
