package views

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/dbtrail/dbtrail/internal/baseline"
)

// TestWriteSuccessMarker_publishesTheSnapshotViewsFile drives the REAL door
// (#1583): baseline.WriteSuccessMarker, whose hook this package's init()
// arms by being linked. Calling WriteSnapshotViews directly would prove the
// generator and skip the wiring, which is the half that can silently fall
// away with an import.
func TestWriteSuccessMarker_publishesTheSnapshotViewsFile(t *testing.T) {
	root := t.TempDir()
	// marked=false: WriteSuccessMarker itself is under test, marker included.
	writeSnapshot(t, root, "2026-04-30T03-00-00Z", false, "kept")
	dir := filepath.Join(root, "2026-04-30T03-00-00Z")
	if err := baseline.WriteSuccessMarker(dir); err != nil {
		t.Fatalf("WriteSuccessMarker: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, baseline.SuccessMarker)); err != nil {
		t.Fatalf("no %s beside the views file: %v", baseline.SuccessMarker, err)
	}
	b, err := os.ReadFile(filepath.Join(dir, SnapshotFileName))
	if err != nil {
		t.Fatalf("no %s was published into the completing snapshot: %v", SnapshotFileName, err)
	}
	sqlText := string(b)

	abs, err := filepath.Abs(dir)
	if err != nil {
		t.Fatal(err)
	}
	// Pinned to its own prefix: absolute paths, so the file works from any
	// working directory on the machine that holds the snapshot.
	if want := "read_parquet('" + filepath.ToSlash(abs) + "/shop/orders.parquet')"; !strings.Contains(sqlText, want) {
		t.Errorf("views file does not read the snapshot's own absolute path %s:\n%s", want, sqlText)
	}
	// No variable, no session step, no pointer, and no claims about a
	// registry this producer never read.
	for _, gone := range []string{"getvariable", "/current/", "archive_state"} {
		if strings.Contains(sqlText, gone) {
			t.Errorf("the in-snapshot file must be pinned and snapshot-scoped; it carries %q:\n%s", gone, sqlText)
		}
	}

	// And it EXECUTES, against a DuckDB whose working directory is NOT the
	// snapshot's — the absolute spelling is what makes that work.
	db, err := sql.Open("duckdb", "")
	if err != nil {
		t.Fatalf("open duckdb: %v", err)
	}
	defer db.Close()
	if _, err := db.Exec(sqlText); err != nil {
		t.Fatalf("DuckDB rejected the published views file:\n%v\n\n--- file ---\n%s", err, sqlText)
	}
	var status string
	if err := db.QueryRow(`SELECT "status" FROM shop.orders`).Scan(&status); err != nil {
		t.Fatalf("query state view: %v", err)
	}
	if status != "kept" {
		t.Errorf("state view read %q; want \"kept\"", status)
	}
}

// TestWriteSuccessMarker_skipsANonSnapshotDirectory pins the same decline
// PublishCurrentPointer makes: `reconstruct --output-format mydumper`
// completes an operator-chosen dump directory through this exact call, and a
// views file has no business there.
func TestWriteSuccessMarker_skipsANonSnapshotDirectory(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "my-dump")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := baseline.WriteSuccessMarker(dir); err != nil {
		t.Fatalf("WriteSuccessMarker: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, SnapshotFileName)); !os.IsNotExist(err) {
		t.Fatalf("a views file was published into a non-snapshot directory (stat err = %v)", err)
	}
	if _, err := os.Stat(filepath.Join(dir, baseline.SuccessMarker)); err != nil {
		t.Fatalf("the decline must not cost the marker: %v", err)
	}
}

// TestSnapshotViewsTempPrefixMatchesTheUploadSkip pins the one literal
// internal/baseline duplicates (it cannot import this package): the staging
// prefix its upload walk skips. Drift means a crashed publish's leftover —
// full of the producing machine's absolute paths — ships to S3 as data.
func TestSnapshotViewsTempPrefixMatchesTheUploadSkip(t *testing.T) {
	if got := baseline.SnapshotViewsStagingPrefix(); got != SnapshotFileTempPrefix {
		t.Fatalf("upload skips %q, the writer stages under %q; a crashed publish's leftover "+
			"would upload as snapshot data", got, SnapshotFileTempPrefix)
	}
}

// TestSnapshotViews_stampsTheProducerVersion: the published file's header
// must name the build that wrote it, like both pre-existing producers do.
func TestSnapshotViews_stampsTheProducerVersion(t *testing.T) {
	SetProducerVersion("v-test-stamp")
	t.Cleanup(func() { SetProducerVersion("") })
	root := t.TempDir()
	writeSnapshot(t, root, "2026-04-30T03-00-00Z", true, "kept")
	sqlText, ok, err := GenerateSnapshotViews(context.Background(),
		filepath.Join(root, "2026-04-30T03-00-00Z"), "/spelled/root")
	if err != nil || !ok {
		t.Fatalf("GenerateSnapshotViews: ok=%v err=%v", ok, err)
	}
	if !strings.Contains(sqlText, "Generated by bintrail v-test-stamp") {
		t.Errorf("header does not stamp the producer version:\n%.300s", sqlText)
	}
}

// TestHeader_dotRootIsNotTheTarballArm pins the guard on the tarball header
// wording: `bintrail views --baseline-dir .` reaches Generate with
// BaselineSource "." and SnapshotScoped FALSE, and must keep the ordinary
// header — "this archive" would frame a CLI file as a downloaded tarball,
// send its reader one directory too deep, and strip a followed file of the
// pointer line that separates it from a pinned one.
func TestHeader_dotRootIsNotTheTarballArm(t *testing.T) {
	out := Generate(Input{
		GeneratedAt:      time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC),
		BaselineSource:   ".",
		BaselineSnapshot: time.Date(2026, 4, 30, 3, 0, 0, 0, time.UTC),
		Baselines: []BaselineTable{
			{Schema: "shop", Table: "orders", Path: "2026-04-30T03-00-00Z/shop/orders.parquet", Rel: "shop/orders.parquet"},
		},
	})
	if strings.Contains(out, "this archive") {
		t.Errorf("a non-snapshot-scoped render with a \".\" root took the tarball header arm:\n%.400s", out)
	}
	// And the arm still exists for the producer that means it.
	tarball := Generate(func() Input {
		in := SnapshotScopedInput(time.Date(2026, 4, 30, 3, 0, 0, 0, time.UTC), []BaselineTable{
			{Schema: "shop", Table: "orders", Path: "/x/shop/orders.parquet", Rel: "shop/orders.parquet"},
		})
		in.RespellBaselines(".")
		return in
	}())
	if !strings.Contains(tarball, "this archive") {
		t.Error("the snapshot-scoped dot-root render lost the tarball header arm")
	}
}

// TestGenerateSnapshotViews_respellsForS3 is the upload half's contract: same
// snapshot, same generator, the destination's own spelling.
func TestGenerateSnapshotViews_respellsForS3(t *testing.T) {
	root := t.TempDir()
	writeSnapshot(t, root, "2026-04-30T03-00-00Z", true, "kept")
	dir := filepath.Join(root, "2026-04-30T03-00-00Z")

	s3root := "s3://bkt/baselines/2026-04-30T03-00-00Z"
	sqlText, ok, err := GenerateSnapshotViews(context.Background(), dir, s3root)
	if err != nil || !ok {
		t.Fatalf("GenerateSnapshotViews: ok=%v err=%v", ok, err)
	}
	if want := "read_parquet('" + s3root + "/shop/orders.parquet')"; !strings.Contains(sqlText, want) {
		t.Errorf("respelled file does not read %s:\n%s", want, sqlText)
	}
	// An s3-spelled file needs the httpfs session setup ahead of its views.
	if !strings.Contains(sqlText, "httpfs") {
		t.Errorf("respelled file carries no S3 preamble:\n%s", sqlText)
	}
	// The local staging path must not leak into the published artifact.
	if strings.Contains(sqlText, filepath.ToSlash(root)) {
		t.Errorf("respelled file leaks the local staging path %s:\n%s", root, sqlText)
	}
}
